### ISSUE TITLE
Scaling aliasing

### ISSUE THREAD

**Issue by fire** [Samsung/thorvg#1007]
Hi, thanks for getting raster image import working.

I noticed that the web viewer seems to have corrupted the display.

![image](https://user-images.githubusercontent.com/32321/140634250-4788d0ad-7d97-4c77-8f4d-4b4fb7e6cbb3.png)

[Godot Planner 2021-11-06.svg.txt](https://github.com/Samsung/thorvg/files/7491810/Godot.Planner.2021-11-06.svg.txt)

**Comment by fire** [comment]
Firefox control screenshot. 
![image](https://user-images.githubusercontent.com/32321/140634338-66694e62-7405-44c9-8d2f-501fcdfad3d1.png)

**Comment by JSUYA** [comment]
@mmaciola It seems to be a colorspace problem in png loader&png library. Could you please check?

**Comment by JSUYA** [comment]
@fire  Thank you for your report. It is different from the issue you raised, but please refer to it
The reason why the arrow of the path is not displayed in our output is that we do not yet support the marker(`<marker>`,  `marker-end`)  :)
![image](https://user-images.githubusercontent.com/7413838/140681140-8e57bcd1-b12f-4f8a-906c-396198dbb578.png)

**Comment by hermet** [comment]
It looks the image is not re-scaled with the higher resolution...

**Comment by fire** [comment]
Good catch on the arrow ends. I didn’t notice. The main issue is the aliasing.

**Comment by hermet** [comment]
@fire ok fundamentally, it's not about thorvg engine issue but resolution problem of the viewer. those fonts are too small at 1152x1152 and current viewer is available up to that resolution. if it allows to increase the resolution higher, the fonts will be looked same with the firefox. if the firefox renders that svg on the lower resolution like thorvg viewer the font drawing will be looked same ugly.

**Comment by hermet** [comment]
@mmaciola do you have any opinion to support higher resolution in viewer side ? for example, ui layout is resized following to the selected resolution.

**Comment by mmaciola** [comment]
I just added custom resolution patch for thorvg viewer: Drag and drop the image, click resolution and type desired one, press enter.

https://user-images.githubusercontent.com/71131832/140932284-b16a3f0f-5e06-4b26-8cd9-1c36855c7d45.mov

Regarding the colorspace of the top right image: it is a global problem of static png loader (not only viewer). LodePng is desired for RGB colorspace and it was only partly changed for BGR. If any non standard png, colorspace may be incorrect (rgb used).

**Comment by hermet** [comment]
@mmaciola thanks for your investigation. i will double-check the colorspace and font quality.

**Comment by hermet** [comment]
@mmaciola btw, could you please polish up the useless scrollbars?

![Untitled](https://user-images.githubusercontent.com/3711518/140941702-a38d694c-e659-4ef7-90da-5c69cbd6a8f4.png)

**Comment by mmaciola** [comment]
@hermet it shouldn't be visible. What browser and version?

**Comment by hermet** [comment]
@mmaciola google chrome, windows edge both are visible,  resolution is 2560x1440 :)

**Comment by hermet** [comment]
update: so ugly fonts are not actually vector images, but bitmap images. 

@mmaciola colorspace actually doesn't have any issued on the local app with ARGB. It looks the viewer is not properly uploaded.

**Comment by mmaciola** [comment]
@hermet The improvement is for scaling of raw images.

Below I attach extracted png from base64 of the svg file, try:
```
    auto picture = tvg::Picture::gen();
    picture->load("/home/mmaciola_local/Downloads/Godot.Planner.Extracted.png");
    picture->size(800, 800);
    if (canvas->push(move(picture)) != tvg::Result::Success) return;
```

![Godot Planner Extracted](https://user-images.githubusercontent.com/71131832/141078867-6ae602fb-3082-4f76-81cc-178b1c539120.png)

![Screenshot from 2021-11-10 09-35-27](https://user-images.githubusercontent.com/71131832/141078993-fac91f60-f9f4-4b9c-aab2-d3a07250e70a.png)

You can also try the resource from the issue https://github.com/Samsung/thorvg/issues/655

Source of this problem is that in tvgLodePng.cpp, colorspace conversion was added only for a single case in getPixelColorsRGBA8. For other cases colorspace is not changed. There are also images that doesn't need conversion and the function is not called at all (see `lodepng_decode`: `lodepng_color_mode_equal(&state->info_raw, &state->info_png.color)`)

**Comment by hermet** [comment]
@fire aliasing issue has been resolved by https://github.com/Samsung/thorvg/pull/1024, just need to upload the binary to the thorvg viewer side.

**Comment by hermet** [comment]
@fire colorspace issue has been fixed as well, tmr i will update the viewer.
