### ISSUE TITLE
Concerns about Jpgd

### ISSUE THREAD

**Issue by fire** [Samsung/thorvg#1027]
Is the Jpgd modified to swap buffer order of images?

`src/loaders/jpg/tvgJpgd.cpp`

1. jpgd needs to be not modified for packaging in Linux distributions.
2. Godot Engine has a copy of Jpgd and it's not good to have two copies of the same code.

**Comment by hermet** [comment]
@fire 
1. It keeps the decoding feature of jpgd. nothing changed actually but changed for thorvg threading and removed unused functions and some conventions.
2. you mentioned linking external library by thorvg is not adaptable for godot. do you have any suggestion?

**Comment by fire** [comment]
I was able to get Godot Engine working at the basic level, I can now review the additional features.

**Comment by fire** [comment]
Closing since this hasn't been a problem.
