### ISSUE TITLE
Not clear error when using invalid path to image in `svg2png` tool

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#1031]
When using
```
svg2png nonexistent.svg
```
I see this warning 
```
Warning: File "nonexistent.svg" is invalid.
```
At first I was thinking that svg file is not supported, but when I checked more files, then I found that I pointed tool to non existent path.
Error should be clear and should print that this file not exists.

**Comment by hermet** [comment]
@qarmin fixed by https://github.com/Samsung/thorvg/commit/15412907b8db5e866609cb964424eb61ad9dc875
```
 Error: Invalid file or path name: "invalidFile.svg"
```
