### ISSUE TITLE
Run tests in CI with address and leak sanitizer

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#1032]
This would help to find issues like in https://github.com/Samsung/thorvg/issues/982 earlier

I suggest to use address and undefined sanitizer instead valgrind
e.g.
```
meson  -Dtools=svg2png -Db_sanitize=address,undefined . build
```

edit:
Hmm.... I see that CI is already setup, but strange that it green mark after commit hash shows only github pages

**Comment by hermet** [comment]
@JSUYA can you help for this?

**Comment by JSUYA** [comment]
> This would help to find issues like in #982 earlier
> 
> I suggest to use address and undefined sanitizer instead valgrind e.g.
> 
> ```
> meson  -Dtools=svg2png -Db_sanitize=address,undefined . build
> ```
@qarmin Hi Thanks for the suggestion.
We don't have any plans yet for adding analyzer to a github action.
We will discuss this suggestion..

> edit: Hmm.... I see that CI is already setup, but strange that it green mark after commit hash shows only github pages
oh I didn't understand. is this what you're talking about? https://github.com/Samsung/thorvg/actions/workflows/actions.yml
The badge on the main page shows the latest result of the action(pull_request).
I know we need to improve on this too.

**Comment by qarmin** [comment]
Yup, now I see that running actions on `push` is not enabled and that is why I didn't see all results(Godot with push and thorvg without as example)
![Screenshot from 2021-11-11 06-34-09](https://user-images.githubusercontent.com/41945903/141243708-e842aafa-3c9a-46d3-b35f-818d343c6f7a.png)

![Screenshot from 2021-11-11 06-34-43](https://user-images.githubusercontent.com/41945903/141243713-6d74092c-1192-4d0e-b97c-cb39b3c29bc1.png)

**Comment by JSUYA** [comment]
I worked to add valgrind test in CI. #1045
Unfortunately, i can't add ASAN.
I tested it on my forked git several times, but asan error was not detected. (unlike local environment)
So I hold adding this to CI.

**Comment by JSUYA** [comment]
It was a meson version problem that I couldn't apply asan.
Now, when a dev makes a PR, CI check for memory leaks and let us know in the comments if there are any problems. :)
https://github.com/Samsung/thorvg/pull/1059
