### ISSUE TITLE
Shape not drawn if multiple lineTo

### ISSUE THREAD

**Issue by mmaciola** [Samsung/thorvg#1079]
If `lineTo()` is called multiple times in a loop (>= 400 times), shape is no more being drawn. 

```
void tvgDrawCmds(tvg::Canvas* canvas)
{
    if (!canvas) return;

    auto shape = tvg::Shape::gen();
    shape->moveTo(WIDTH/2, HEIGHT/2);
    shape->stroke(255, 0, 0, 255);
    shape->stroke(4);
    for (int i = 0; i < 600; i++) {
        shape->lineTo(rand() % WIDTH, rand() % HEIGHT);
    }

    if (canvas->push(move(shape)) != tvg::Result::Success) return;
}
```

**Comment by mmaciola** [comment]
The above snippet sometimes also crashes with `signal SIGABRT` on [line 117 of tvgShapeImpl.h](https://github.com/Samsung/thorvg/blob/e90f040208c8b3e86184db871b9499cd92ad992b/src/lib/tvgShapeImpl.h#L117) (`reservePts()` function). I never observed a crash on `reserveCmd()`.

**Comment by hermet** [comment]
The current problem is that it's too complex as one single shape.

**Comment by mmaciola** [comment]
I was creating a benchmark to test how rendering time changes with more shapes added.
Thanks. As you suggest I tested with less random points (less complex) and found out that this problem nor SIGABRT problem no more occurs. I am closing it as an issue, won't occur in practical cases.

```
void drawDemoShape() {
    int x = WIDTH/2, y = HEIGHT/2;
    auto shape = Shape::gen();
    shape->moveTo(x, y);
    shape->stroke(255, 255, 0, 255);
    shape->stroke(4);
    
    for (int i = 0; i < 1000; i++) {
        x += (rand() % 21) - 10;
        y += (rand() % 21) - 10;
        shape->lineTo(x, y);
    }
    
    swCanvas->push(move(shape));
}
```
