### ISSUE TITLE
Undefined sanitizer runtime error when converting svg file

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#1149]
Command:
```
/home/rafal/test/thorvg/build/src/bin/svg2png/svg2png /home/rafal/Desktop/SV/file0.svg -r 1x1
```

Error
```
../src/loaders/svg/tvgSvgLoader.cpp:1909:19: runtime error: null pointer passed as argument 2, which is declared to never be null
```
https://github.com/Samsung/thorvg/blob/6fb0984b49a578bbc7e8289270bd7fdb6069b451/src/loaders/svg/tvgSvgLoader.cpp#L1909

[file729.svg.zip](https://github.com/Samsung/thorvg/files/7871659/file729.svg.zip)

**Comment by hermet** [comment]
confirmed the fix
