### ISSUE TITLE
Different color of object after converting it to png

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#1162]
![Screenshot from 2022-01-18 17-31-48](https://user-images.githubusercontent.com/41945903/149978606-12c25c71-6c90-4af7-bbb9-8a032f336158.png)

[AAA.zip](https://github.com/Samsung/thorvg/files/7890765/AAA.zip)

**Comment by qarmin** [comment]
Here entire object is missing
[90.zip](https://github.com/Samsung/thorvg/files/7890800/90.zip)
![Screenshot from 2022-01-18 17-36-06](https://user-images.githubusercontent.com/41945903/149979300-fedd7aee-21fb-4dcb-b804-94c9caab72b2.png)

**Comment by mgrudzinska** [comment]
The problem with 90.svg is solved in #1165.

54.svg and 60.svg - both are using css styling, which will be supported in tvg very soon (i checked both files in pr #1160 and they look correct)
