### ISSUE TITLE
SVG of REC-SVG11-20030114.pdf issues

### ISSUE THREAD

**Issue by fire** [Samsung/thorvg#1177]
PDF of SVG11 spec converted to svg and crushed using svg cleaner has sporadic issues.

https://www.w3.org/TR/2003/REC-SVG11-20030114/REC-SVG11-20030114.pdf

[svg-spec.zip](https://github.com/Samsung/thorvg/files/7969858/svg-spec.zip)

```bash
pdf2svg REC-SVG11-20030114.pdf REC-SVG11-20030114-%03d.svg all
```
PDF.
![image](https://user-images.githubusercontent.com/32321/151774207-cc2b56b5-e393-481a-8f0a-0fb88e6431d8.png)

Desktop.
![image](https://user-images.githubusercontent.com/32321/151775826-cefeb684-8dbd-402d-8e4a-12b9a18b222e.png)

ThorVG.
![image](https://user-images.githubusercontent.com/32321/151774258-9a98195e-fda1-4043-b9e1-a9c4e630b291.png)

Was wondering if I was using any forbidden features.

**Comment by mgrudzinska** [comment]
we don't have "forbidden features", we have those, that are not supported YET :)

I think that in this case the 'symbol' tag is the problem - we need to implement it in the svg_loader.

**Comment by mgrudzinska** [comment]
symbol is implemented, but there is still an issue with image scaling.

**Comment by hermet** [comment]
@mgrudzinska Your patch has been applied and it looks working fine. Could you please explain more detail about the image scaling issue?

**Comment by mgrudzinska** [comment]
@hermet the issue is solved by #1185

**Comment by fire** [comment]
My acceptance criteria is when the https://samsung.github.io/thorvg.viewer/ viewer shows the proper rendering. Exciting though.

**Comment by hermet** [comment]
@mgrudzinska do you think the svg styling feature is ready to go? it so, we can release v0.8 in the end of this week (26 ~ 27),

**Comment by mgrudzinska** [comment]
@hermet I'd like to make some tests tmr and then I'll confirm. I'm not sure right now.

**Comment by fire** [comment]
I'm having trouble confirming this.
