### ISSUE TITLE
default value of aspect ratio is "xMinYMid meet"

### ISSUE THREAD

**Issue by mgrudzinska** [Samsung/thorvg#1181]
in an svg file the default value of the `preserveAspectRatio` attribute is `xMidYMid meet`
TVG supports only `none` value for this attrib. Anything else is interpreted as the default value, which seems to be `xMinYMid meet` instead of `xMidYMid`

**Comment by mgrudzinska** [comment]
I think that the def value is '"xMinYMin meet"'.  Either way it should be changed

**Comment by hermet** [comment]
@mgrudzinska could you please close this if this is resolved by the commits?

**Comment by mgrudzinska** [comment]
@hermet I took me some time to respond :D
The issue is not solved, I try to solve it in the next week

**Comment by mgrudzinska** [comment]
solved in #1249
