### ISSUE TITLE
Lost blue on the United Nations flag

### ISSUE THREAD

**Issue by fire** [Samsung/thorvg#1186]
![image](https://user-images.githubusercontent.com/32321/152932579-baf8d12b-e11e-4259-ba58-2020c0e30810.png)
![UN_emblem_blue - Copy](https://user-images.githubusercontent.com/32321/152932619-bd3d6921-72df-4f09-856b-f9743ae32a14.svg)

**Comment by fire** [comment]
Reference https://github.com/godotengine/godot/issues/48243

**Comment by mgrudzinska** [comment]
@fire today the css styling was merged :) 
it's blue now

**Comment by hermet** [comment]
The css styling feature must be included in thorvg v0.8, its viewer as well.
The next major up version will be released in early March.

**Comment by hermet** [comment]
@fire https://github.com/Samsung/thorvg/releases/tag/v0.8.0
the viewer has been updated as well.

**Comment by fire** [comment]
Confirmed fixed. :+1:
