### ISSUE TITLE
How to load an image only once but re-use it?

### ISSUE THREAD

**Issue by projectitis** [Samsung/thorvg#1202]
Hi all - 

I want to load a picture ONCE, but render it many times throughout the life of my application.
In the [example](https://github.com/Samsung/thorvg/blob/master/src/examples/PicturePng.cpp) I have to move() the picture to the canvas, which will destroy the picture when I call canvas->clear() because the canvas owns the unique_ptr and will now release it.

This is a very simplified example:
```
auto picture = tvg::Picture::gen();
picture->load(EXAMPLE_DIR"/test.png");
canvas->push(move(picture));

// Now, later (in a render loop) I want to do this
while (rendering) {
    canvas->clear();
    canvas->push(picture); // But picture is now destroyed
}
```

How do I load the picture once but keep re-using it?

**Comment by projectitis** [comment]
I found the solution today by looking at some of the examples :)
This one is the most helpful:  https://github.com/Samsung/thorvg/blob/master/src/examples/DirectUpdate.cpp

You can grab a pointer to the picture so that it can be manipulated outside of the canvas. Then you can update the canvas to apply the changes.

```
auto picture = tvg::Picture::gen();
picture->load(EXAMPLE_DIR"/test.png");
tvg::Picture* pictureRef = picture->get(); // Retain a reference
canvas->push(move(picture));

// Now, later (in a render loop) I want to do this
while (rendering) {
    //canvas->clear(); do not clear
    pictureRef->transform( transform ); // Do changes to picture
    canvas->update(pictureRef); // Force canvas to update the picture
}
```

**Comment by hermet** [comment]
@projectitis great! :)
