### ISSUE TITLE
Crash on REC-SVG11-20030114-299.svg

### ISSUE THREAD

**Issue by fire** [Samsung/thorvg#1205]
[REC-SVG11-20030114-299](https://user-images.githubusercontent.com/32321/157244674-33b830b7-3a45-480f-a26f-794edff45f82.svg)

![image](https://user-images.githubusercontent.com/32321/157244774-25605597-a9b3-4730-a8cc-fb309f26d37e.png)

Will check web viewer

**Comment by fire** [comment]
```outline.types``` is null in these cases.

**Comment by fire** [comment]
https://github.com/Samsung/thorvg/files/7969858/svg-spec.zip contains a few hundred pages of samples. Will try to make them bite sized bug reports.

**Comment by fire** [comment]
Will check something, might be a corrupted build.

**Comment by hermet** [comment]
@fire ok, I will check it tmr.

**Comment by hermet** [comment]
@fire + it would be better if you share the size of the picture you set for the issue case.

**Comment by fire** [comment]
Sorry for the scare. False alarm, I was using the 0.7.1 version of thorvg to test mistakenly.
