### ISSUE TITLE
Picture: Implement image meshes

### ISSUE THREAD

**Issue by projectitis** [Samsung/thorvg#1218]
The next version of the Rive renderer requires support for image meshes. ThorVG currently has support for a texture map (2 triangles) but would need to allow mapping via an arbitrary mesh.

**Comment by projectitis** [comment]
@hermet @mgrudzinska @JSUYA @mmaciola I have added code for the low-level drawing of triangle meshes, based existing code in `tvgSwRasterTexmap.cpp`. Note that this is theoretical until I make/modify a Paint that supports it and can run and test it :)
Refer to [this commit on my fork](https://github.com/DeriveSDK/thorvg/commit/74f3af2191c635ae7941e42f5a9921f4daac0021).

My question is - how should the Paint look?  We have a few different options - what is your preference? (also feel free to suggest any alternative)

Option 1: Build it into picture
```
auto picture = tvg::Picture::gen();
picture->load(EXAMPLE_DIR"/test.png");
Polygon triangles[4] = { /* vertex data here (points + UVs) */ }
picture->mesh(&triangles, 4); // Define a mesh made of 4 triangles
canvas->push(move(picture));
```

Option 2: Extend Picture, but same thing:
```
// class ImageMesh extends Picture
auto mesh = tvg::Mesh::gen();
mesh ->load(EXAMPLE_DIR"/test.png");
Polygon triangles[4] = { /* vertex data here (point + UVs) */ }
mesh ->mesh(&triangles, 4);
canvas->push(move(mesh));
```

Option 3: Mesh which can share picture (this is my preference)
```
auto picture = tvg::Picture::gen();
picture->load(EXAMPLE_DIR"/test.png");

// class Mesh extends Paint
auto mesh1 = tvg::Mesh::gen();
mesh1->texture( picture.get() );
mesh1->mesh({ /* vertex data here (points + UVs) */ }, 7 );
canvas->push(move(mesh1));

auto mesh2 = tvg::Mesh::gen();
mesh2->texture( picture.get() );
mesh2->mesh({ /* vertex data here (points + UVs) */ }, 18 );
mesh2->mesh({ /* vertex data here (points + UVs) */ }, 3, true ); // Append more triangles to the mesh
canvas->push(move(mesh2));
```

Thoughts?

**Comment by JSUYA** [comment]
I think option 1's approach is appropriate. :)  👍👍   @hermet ?

  +)  I'm not sure if mesh is a function that can only be used in picture class.
Does the same apply to SVG images?

**Comment by projectitis** [comment]
Normally a mesh is a series of triangles with a bitmap texture mapped to it. In my opinion, the UV mapping step would be very difficult if the texture was a vector. My preference would be to render the SVG to a bitmap and then use that for drawing a mesh. Is it possible to render/convert an SVG Shape to a Picture?

**Comment by JSUYA** [comment]
> My preference would be to render the SVG to a bitmap and then use that for drawing a mesh. Is it possible to render/convert an SVG Shape/Scene to a Picture?

Getting a rasterized scene and using it for a mesh seems to be very complicated.
I thought option 1 was the simplest. But when I think of the picture loaded with SVG image, I think I was wrong.
I think option 3 can support to vector objects(shape/scene) as well as svg images, but the implemention seems to be too complicated.

So I think you can make it simple with option 2 and consider option 3 later.

**Comment by projectitis** [comment]
Thanks @JSUYA - I actually started Option 3 yesterday and it was very complicated, so I switched to Option 1. I will see how it goes. If it is successful, it should be simple to convert it to Option 2 or Option 3 later :)

**Comment by hermet** [comment]
@projectitis @JSUYA  Simple is the best. the option1 is enough to go IMHO. 

For supporting vector meshes, as @JSUYA mentioned, tvg can go through 2 render pass, it raterizes the vector scene to bitmap in the first step, next render the mesh using the bitmap as the texture source.

We can return *UNSUPPORTED* for the vector sources such as svgs in the first version, later we can support them if there are demands.  Though I can imagine the demand but is it really necessary...? i'm not sure now :)

**Comment by hermet** [comment]
closed by this:
https://github.com/Samsung/thorvg/commit/3dd65dfed00849f0bd9d0bb0ade177fa961cd7a5
