### ISSUE TITLE
examples, compilation error on Windows: uint is not known

### ISSUE THREAD

**Issue by vtorri** [Samsung/thorvg#1247]
the error message is:

```
../src/examples/Performance.cpp:32:8: error: 'uint' does not name a type; did you mean 'u_int'?
   32 | static uint cnt = 0;
      |        ^~~~
      |        u_int
```

**Comment by vtorri** [comment]
afaics, it's the only compilation error

**Comment by hermet** [comment]
It looks we can replace uint -> unsigned int. or unsigned?

**Comment by vtorri** [comment]
yes but there is some  inconsistance, as uint32_t is also used.

**Comment by vtorri** [comment]
i would not use `unsigned`

**Comment by hermet** [comment]
uint32_t makes sense to me. please submit patches otherwise i will fix it soon.

**Comment by vtorri** [comment]
@hermet i've never been able to create different pull requests, each time they are merged into a single PR. If you can give me the exact git commands in the terminal, i'll do it. Otherwise, I have to wait for my svg2png PR to be merged

**Comment by hermet** [comment]
I normally do create a new branch for new a PR.

$git branch myfix1
$git checkout myfix1
//MODIFY CODE
$git commit 
$git push origin myfix1 

Does this helpful? If my understanding is correct...

**Comment by vtorri** [comment]
does not work, I still have the 2 commits in 1 PR: https://ibb.co/mHfwhWz

**Comment by hermet** [comment]
https://github.com/Samsung/thorvg/commit/5fa8aac2aa856c54d7084f9fb76f936e05042008

**Comment by hermet** [comment]
> does not work, I still have the 2 commits in 1 PR: https://ibb.co/mHfwhWz

I think you didn't reset the base branch before working like this??

$git checkout master
$git reset origin/master --hard
$git branch new_branch
$git checkout new_branch
$git commit -m "xxx"
$git push origin new_brach
