### ISSUE TITLE
Windows and clang: compilation error in src/loaders/svg/tvgSvgSceneBuilder.cpp

### ISSUE THREAD

**Issue by vtorri** [Samsung/thorvg#1252]
error:

```
../src/lib/tvgMath.h:52:56: error: use of undeclared identifier 'M_PI_2'
   if (radian < FLT_EPSILON || mathEqual(radian, float(M_PI_2)) || mathEqual(radian, float(M_PI))) return true;
                                                       ^
../src/lib/tvgMath.h:52:92: error: use of undeclared identifier 'M_PI'
   if (radian < FLT_EPSILON || mathEqual(radian, float(M_PI_2)) || mathEqual(radian, float(M_PI))) return true;
                                                                                           ^
../src/lib/tvgMath.h:122:37: error: use of undeclared identifier 'M_PI'
    auto radian = degree / 180.0f * M_PI;
                                    ^
```

Problem:

 * First, on Windows, one must define `_USE_MATH_DEFINES` before including `math.h` to get M_PI and other macros.
 * tvgSvgSceneBuilder.cpp includes first `cstring`, which includes `math.h`, and **after**, it includes `tvgMath.h`. So `_USE_MATH_DEFINES` is not defined when `math.h` is included from `cstring`
 * when `tvgMath.h` is included, `_USE_MATH_DEFINES` is defined, but `math.h` is not included anymore. Hence the problem.

solution: in tvgSvgSceneBuilder.cpp, include `tvgMath.h` before the strings includes

or else define `_USE_MATH_DEFINES` globally

what do you think of this solutions ?

**Comment by hermet** [comment]
either one fine to me.
