### ISSUE TITLE
ThorVG resize images differently than rsvg or inkscape

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#1258]
When resizing image in both directions, then if image is not square, then resize image only according to its aspect ratio, center it, and rest image is filled with alpha.

```
svg2png 3492.svg -r 500x500
rsvg-convert -o abcd.png abcd.svg -w 500 -h 500
```

![Screenshot from 2022-08-27 08-31-15](https://user-images.githubusercontent.com/41945903/187018283-f16149ba-cc04-46d7-9aed-03406e468003.png)

[svg.zip](https://github.com/Samsung/thorvg/files/9437422/svg.zip)

**Comment by mgrudzinska** [comment]
@qarmin thx for this example. This is solve in #1249 which is currently under discussion.

**Comment by hermet** [comment]
verified. thanks all.
