### ISSUE TITLE
Change the func type of Accessor::access() to std::function

### ISSUE THREAD

**Issue by JSUYA** [Samsung/thorvg#1275]
Currently, the `func` parameter type of the access() api is a function pointer.
```
std::unique_ptr<Picture> access(std::unique_ptr<Picture> picture, bool(*func)(const Paint* paint)) noexcept;
```
There are limited ways to pass user data to the func function. So to support this we can add `void* userData` or use std::function.
Existing APIs should be deprecated and new APIs should be added.
ex)
```
std::unique_ptr<Picture> access(std::unique_ptr<Picture> picture, const std::function<bool(const Paint* paint)>) noexcept;
```

**Comment by hermet** [comment]
yes i think std::function sounds reasonable.

**Comment by JSUYA** [comment]
Added new beta api. User can use std::function with this api.
`std::unique_ptr<Picture> set(std::unique_ptr<Picture> picture, std::function<bool(const Paint* paint)> func) noexcept;`
