### ISSUE TITLE
Chain Compositions

### ISSUE THREAD

**Issue by pvigier** [Samsung/thorvg#1295]
Hello,

Is it possible to chain compositions?

I would like to start with a colored rectangle and then remove parts from it using masking several times.

I tried this approach using a scene to specify the second composition but only the first one is taken into account:

```cpp
// Color
auto color = tvg::Shape::gen();
color->appendRect(0, 0, 400, 400, 0, 0);
color->fill(255, 0, 0, 255);
// Shield
auto shield = tvg::Picture::gen();
shield->load("shield.svg");
color->composite(std::move(shield), tvg::CompositeMethod::AlphaMask);
// Field
auto field = tvg::Picture::gen();
field->load("field.svg");
auto scene = tvg::Scene::gen();
scene->push(std::move(color));
scene->composite(std::move(field), tvg::CompositeMethod::AlphaMask);
canvas->push(std::move(scene));
```
Here is what I got:
![result](https://user-images.githubusercontent.com/934316/208699507-cccb7b0e-04cd-4833-95f7-fd67194fe1b9.png)
And here is what I would like to get:
![expected](https://user-images.githubusercontent.com/934316/208699573-5950c5e1-9a31-42ce-bceb-4df8b89965e5.png)

Here are the two input files:
![shield](https://user-images.githubusercontent.com/934316/208699690-c6ad771e-0b51-419f-aa4d-e396d83d6c61.svg)
![field](https://user-images.githubusercontent.com/934316/208699728-1ddfe45a-96a5-44fa-88f4-fd8a9114fcf1.svg)

Best regards,
Pierre

**Comment by hermet** [comment]
it's supposed to be working, will let you know the result after checking the internals.

**Comment by hermet** [comment]
@pvigier it's supposed to be working, will let you know the result after checking the internals.

**Comment by hermet** [comment]
@pvigier Hmm need to improve it, here is a quick easier suggestion you could use it right now.

`
auto color = tvg::Shape::gen();
color->appendRect(0, 0, 400, 400, 0, 0);
color->fill(255, 0, 0, 255);

// Shield
auto shield = tvg::Picture::gen();
shield->load("./shield.svg");

// Field
auto field = tvg::Picture::gen();
field->load("field.svg");

shield->composite(std::move(field), tvg::CompositeMethod::AlphaMask);

color->composite(std::move(shield), tvg::CompositeMethod::AlphaMask);

**Comment by hermet** [comment]
confirmed fixed.
