### ISSUE TITLE
TaskScheduler Optimization

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#140]
Current TaskScheduler uses c++ promise&future which are allocates a lot of memory during frames.

tvgTaskScheduler.h:

struct Task
    promise<void> sender;
    future<void>  receiver;
 ...

We can consider to apply own synchronization mechanism by using mutex locks.

**Comment by hermet** [comment]
https://github.com/Samsung/thorvg/pull/142

**Comment by smohantty** [comment]
![Screenshot from 2020-11-09 14-32-42](https://user-images.githubusercontent.com/34466874/98503662-6cc2a100-2298-11eb-8d5e-6838ab6d2b4e.png)

**Comment by hermet** [comment]
https://github.com/Samsung/thorvg/pull/142
