### ISSUE TITLE
Seg fault if picture pushed without translate

### ISSUE THREAD

**Issue by mmaciola** [Samsung/thorvg#150]
There is a segmentation fault if picture is pushed without translate or with translate(0, 0); before push call.

To reproduce:
In [PixelImage.cpp example](https://github.com/Samsung/thorvg/blob/master/src/examples/PixelImage.cpp#L31) comment line:
`picture->translate(400, 250);`

**Comment by JSUYA** [comment]
It was fixed with patch #155. Thank you for your report :)
