### ISSUE TITLE
Extend ThorVG Viewer to print non-supported svg elements.

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#152]
Unsupported SVG Elements used = ["xxx", "yyy", "zzz"] ??

**Comment by kimcinoo** [comment]
It is able to show the printf output using wasm.
We need to make a decision if we are using printf or not.

**Comment by JSUYA** [comment]
https://github.com/Samsung/thorvg/pull/165
With this patch we can differentiate elements and attributes that are not parsed.
If we have a suitable log system we can use it.
Perhaps once the log system is implemented we can process to do this.

**Comment by kimcinoo** [comment]
[thorvg.viewer commit]
https://github.com/Samsung/thorvg.viewer/commit/a9181da1ffbfd604ffa1028053bf6d1ac9f08b5f

[result]
![thorvg viewer unsupported attrbutes](https://user-images.githubusercontent.com/912708/102301959-51376e00-3f9b-11eb-9ad5-fed2e80a2e30.png)

**Comment by kimcinoo** [comment]
[thorvg.viewer commit]
https://github.com/Samsung/thorvg.viewer/commit/d92a3678381a0f8ed3eec79700391b20b1fb4603

[result]
![thorvg viewer neat output](https://user-images.githubusercontent.com/912708/102306551-dc1d6600-3fa5-11eb-82c3-02a907db77e9.png)

**Comment by JSUYA** [comment]
Good!!
