### ISSUE TITLE
Low Quality Composition Issue

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#176]
See Examples/Opacity:

![shot-2020-12-09_14-16-59](https://user-images.githubusercontent.com/3711518/101588286-60fa0400-3a29-11eb-8073-21a46fa27b5b.png)

**Comment by JSUYA** [comment]
This problem has already been mentioned in https://github.com/Samsung/thorvg/issues/123

**Comment by hermet** [comment]
https://github.com/Samsung/thorvg/pull/185
