### ISSUE TITLE
Need ignore list for svg unsupported feature.

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#201]
Does this necessary to print?

SVG: Unsupported attributes used [Elements type: Doc][Attribute: xmlns:inkscape]
SVG: Unsupported attributes used [Elements type: Doc][Attribute: xmlns:rdf]
SVG: Unsupported attributes used [Elements type: Doc][Attribute: xmlns:cc]
SVG: Unsupported attributes used [Elements type: Doc][Attribute: xmlns:dc]
SVG: Unsupported attributes used [Elements type: Doc][Attribute: xmlns:sodipodi]
SVG: Unsupported attributes used [Elements type: Doc][Attribute: xmlns:ns1]
SVG: Unsupported attributes used [Elements type: Doc][Attribute: id]
SVG: Unsupported attributes used [Elements type: Doc][Attribute: sodipodi:docname]
SVG: Unsupported attributes used [Elements type: Doc][Attribute: version]
SVG: Unsupported attributes used [Elements type: Doc][Attribute: inkscape:version]

If so, what user supposed to do?

**Comment by JSUYA** [comment]
These messages have been fixed from #358.
