### ISSUE TITLE
If shape uses gradient and mask together, mask does not work normally.

### ISSUE THREAD

**Issue by JSUYA** [Samsung/thorvg#243]
[code]
```cpp
diff --git a/src/examples/Masking.cpp b/src/examples/Masking.cpp
index 8d517ef..d63b1af 100644
--- a/src/examples/Masking.cpp
+++ b/src/examples/Masking.cpp
@@ -14,7 +14,18 @@ void tvgDrawCmds(tvg::Canvas* canvas)
     //Solid Rectangle
     auto shape = tvg::Shape::gen();
     shape->appendRect(0, 0, 400, 400, 0, 0);
-    shape->fill(0, 0, 255, 255);
+    //LinearGradient
+    auto fill = tvg::LinearGradient::gen();
+    fill->linear(0, 0, 400, 400);
+
+    //Gradient Color Stops
+    tvg::Fill::ColorStop colorStops[2];
+    colorStops[0] = {0, 0, 0, 0, 255};
+    colorStops[1] = {1, 255, 255, 255, 255};
+
+    fill->colorStops(colorStops, 2);
+
+    shape->fill(move(fill));
 
     //Mask
     auto mask = tvg::Shape::gen();

```

[screen shot]
![image](https://user-images.githubusercontent.com/7413838/107931405-88d48d80-6fbf-11eb-8a3e-9bf0571c90ba.png)

**Comment by patrykka** [comment]
there is same problem with mask+gradient when defined in svg file.
Visible in Svg example:
![image](https://user-images.githubusercontent.com/5477159/109015622-9cfe4600-76b5-11eb-9da3-3263f8116508.png)

**Comment by patrykka** [comment]
@JSUYA @hermet 
Could you please share your thoughts how gradients + composition should be implemented?
My idea is to add some function like rasterGradientShape inside renderShape, what do you think?
