### ISSUE TITLE
Is is possible to use CubicTo to handle QuadraticTo?

### ISSUE THREAD

**Issue by AfflatusX** [Samsung/thorvg#264]
Hi! Thanks for the amazing library! We're trying it out on an embedded device with some svg instructions. I noticed the SVG contains quadraticCurveTo but Thorvg only supports CubicTo. 

I'm a noob in the SVG terminology/math, but looking at https://github.com/Samsung/thorvg/commit/be6615d93e0488f239edf62b61dd6ed33a9a36c5 - it feels like it's possible to use existing CubicTo API to handle QuadraticTo?

Or even better - is it possible to add QuadraticTo API?  Thanks in advance!

**Comment by JSUYA** [comment]
Thank you for your interest in our project.
We don't yet have plans for quadratic_to api.
quadratic_to can be drawn using cubic_to.

Please refer to two well-described links below.
https://stackoverflow.com/questions/3162645/convert-a-quadratic-bezier-to-a-cubic-one
https://stackoverflow.com/questions/9485788/convert-quadratic-curve-to-cubic-curve

If you use thorVG's cubicTo API, you can use it like this.
```cpp
auto shape1 = tvg::Shape::gen();
shape1->moveTo(100, 100);
shape1->cubicTo(133, 133, 166, 133 , 200, 100);
shape1->stroke(0, 0, 255, 255);
shape1->stroke(3);
if (canvas->push(move(shape1)) != tvg::Result::Success) return;

auto shape2 = tvg::Shape::gen();
shape2->moveTo(100, 300);

float startx = 100.0f;
float starty = 300.0f;

//Quadratic To
float ctrlx = 150.0f;
float ctrly = 350.0f;
float endx = 200.0f;
float endy = 300.0f;

float ctrl_x0 = (startx + 2 * ctrlx) * (1.0 / 3.0);
float ctrl_y0 = (starty + 2 * ctrly) * (1.0 / 3.0);
float ctrl_x1 = (endx + 2 * ctrlx) * (1.0 / 3.0);
float ctrl_y1 = (endy + 2 * ctrly) * (1.0 / 3.0);
shape2->cubicTo(ctrl_x0, ctrl_y0, ctrl_x1, ctrl_y1 , endx, endy);
shape2->stroke(255, 0,0 , 255);
shape2->stroke(3);
if (canvas->push(move(shape2)) != tvg::Result::Success) return;

```
![image](https://user-images.githubusercontent.com/7413838/109605702-ef81ab80-7b68-11eb-9a1e-c191788c9497.png)
