### ISSUE TITLE
Issue with masking

### ISSUE THREAD

**Issue by mgrudzinska** [Samsung/thorvg#268]
The problem does not occur every time

Screens from AnimateMasking.cpp with a small change in the position of the circle to highlight the problem:

    //mask
    auto maskShape = tvg::Shape::gen();
    pMaskShape = maskShape.get();
    maskShape->appendCircle(100, 180, 125, 125); //change
    maskShape->fill(0, 0, 0, 125);
    maskShape->stroke(25, 25, 25, 255);
    maskShape->stroke(tvg::StrokeJoin::Round);
    maskShape->stroke(10);
    canvas->push(move(maskShape));

    auto mask = tvg::Shape::gen();
    pMask = mask.get();
    mask->appendCircle(100, 180, 125, 125);  //change
    mask->fill(255, 0, 0, 255);

![anim1_bad](https://user-images.githubusercontent.com/67589014/109438556-dbd02b00-7a2a-11eb-894a-796ccafd5af6.PNG)
![anim2_bad](https://user-images.githubusercontent.com/67589014/109438562-df63b200-7a2a-11eb-9ed5-63d39c390233.PNG)

**Comment by hermet** [comment]
https://github.com/Samsung/thorvg/commit/6601c93899b34791ec2fdb0645a7682838bd5ba2
