### ISSUE TITLE
API Documentation 

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#27]
C++/C APIs are not documented yet. We need to fill it.

**Comment by hermet** [comment]
@JSUYA  @mgrudzinska  @mihashco  

We are going to release thorvg v0.1.0 soon,
before that please fill / revise api docs if you are possible. Thanks!

**Comment by JSUYA** [comment]
Hi @mgrudzinska  @mihashco
#348 is merged.
I refer to EFL's Documentation and write some of the APIs' documentation. (efl/src/lib/evas/Evas_Legacy.h)
It is basically based on the doxygen document format.
Please fill in the documentation in area marked with `...`.
And if there is a problem with the previously written documenation, please make a fix commit.

**Comment by mgrudzinska** [comment]
@JSUYA I'm on it.

**Comment by mgrudzinska** [comment]
@JSUYA I'm still on it, hopefully I'll finish tomorrow. 
fyi - I have some problems with enum classes - I can't see them in the html/latex files.

**Comment by mgrudzinska** [comment]
the problem with enum class is solved after I made some changes in the doxygen configuration file:
```
ENABLE_PREPROCESSING = YES
MACRO_EXPANSION      = YES
EXPAND_ONLY_PREDEF   = YES
PREDEFINED           = TVG_EXPORT
```
so probably the config should be added to the repo as well
