### ISSUE TITLE
SVG Issue 

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#287]
dst.svg  in examples is broken after this patch:

commit 2bb108b2f13432ac140d9be08daae189fe9c61c5
Author: Mira Grudzinska <m.grudzinska@samsung.com>
Date:   Sun Mar 7 16:02:04 2021 +0100

    svg_loader: limiting the ploted area of svg to viewBox

    The 'viewBox' element given in the svg file determines
    the coordinates of the plotted area. ClipPath used in Svg loader.

![shot-2021-03-12_12-51-06](https://user-images.githubusercontent.com/3711518/110889569-bea43200-8331-11eb-9d56-a428d7e07123.jpg)

**Comment by mgrudzinska** [comment]
The #277 PR shapes were clipped instead of the final scene. It was the reason why the dst.svg was not properly drawn.
PR #290 fixes this.
But currently there is the #291 issue  and it has to be solved first, before PR #290 can be merged.
