### ISSUE TITLE
Support Masking Method

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#31]
There is a requirement to apply vector object as masking source.

ex)
auto maskSource;   //This paint is used for masking source 
auto maskTarget;    //This paint is used for masking target

maskTarget->composite(maskSource, AlphaBlend );    //Now, maskTarget can be masked(or clipped) by maskSource.

**Comment by hermet** [comment]
Please mind this interfaces for implementing basic maksing model.
enum CompMethod { MaskAlpha };
bool Paint::composite(unique_ptr<Paint> paint, CompMethod method);


ex)
auto scene = tvg::Scene::gen();
auto mask = tvg::Scene::gen();

scene->composite(move(mask), CompMethod::MaskAlpha);

**Comment by hermet** [comment]
Alpha, InvertedAlpha, Lumininans, Inverted Lumininans

**Comment by hermet** [comment]
https://github.com/Samsung/thorvg/pull/207

**Comment by hermet** [comment]
Still need to enhance gradients + Inverse Alpha Masking.

**Comment by patrykka** [comment]
[213](https://github.com/Samsung/thorvg/pull/213)
