### ISSUE TITLE
Gradient Color Issue

### ISSUE THREAD

**Issue by taehyub** [Samsung/thorvg#327]
stroke gradient looks wrong
patch: sw_engine raster: refactoring the gradient rastering functions (9d7a264610782ba9066a7369349306f642dca570)
normal case
![image](https://user-images.githubusercontent.com/9302965/114137252-e0033880-9946-11eb-9493-0a30f68b34e3.png)
looks wrong
![image](https://user-images.githubusercontent.com/9302965/114136988-7e42ce80-9946-11eb-9707-ff817550c69e.png)

**Comment by hermet** [comment]
=> $https://github.com/rive-app/rive-tizen
=> $meson install (as it guided, but please enable example)
=> launch examples in the build result. :-)

**Comment by mgrudzinska** [comment]
This was my mistake (copy/paste...) and it is solved in #326 
Thanks !

**Comment by hermet** [comment]
@taehyub @mgrudzinska  verified. thanks a lot !
