### ISSUE TITLE
Opacity duplicate issue of "fill-opacity" and "opacity" (SVG)

### ISSUE THREAD

**Issue by JSUYA** [Samsung/thorvg#38]
In SVG
The fill-opacity attribute only applies to fil.
The opaicty attribute is applied to fill and stroke.
In tvg, Alpha of shape and Alpha of stroke are applied respectively.

In SVG, fill-opacity 0.5 is
shape->fill(,,, 255*0.5)

But
opacity 0.5 is
shape->fill(,,, 255*0.5)
shape->stroke(,,, 255*0.5)

It goes like this.
![image](https://user-images.githubusercontent.com/7413838/92698977-ff71bd00-f387-11ea-9670-28df65204232.png)

(testShape.cpp)
```c
void tvgDrawCmds(tvg::Canvas* canvas)
{
    if (!canvas) return;

    //Prepare a Shape (Rectangle + Rectangle + Circle + Circle)
    auto shape1 = tvg::Shape::gen();
    shape1->appendRect(0, 0, 200, 200, 0, 0);          //x, y, w, h, rx, ry      
    shape1->appendRect(100, 100, 300, 300, 100, 100);  //x, y, w, h, rx, ry
    shape1->appendCircle(400, 400, 100, 100);          //cx, cy, radiusW, radiusH
    shape1->appendCircle(400, 500, 170, 100);          //cx, cy, radiusW, radiusH
    shape1->fill(255, 255, 0, 128);                    //r, g, b, a            
    shape1->stroke(255, 0, 0, 128);       //color: r, g, b, a
    shape1->stroke(40);                       //width: 10px

    canvas->push(move(shape1));
}   
```
But the result we want is

```html
<!-- Learn about this code on MDN: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-opacity -->

<svg viewBox="0 0 400 100" xmlns="http://www.w3.org/2000/svg">

  <!-- Fill opacity as a number -->
  <circle cx="150" cy="50" r="40"
          opacity="0.5" fill-opacity="0.5" stroke="#FF0000" stroke-width="20"/>

</svg>
```
![image](https://user-images.githubusercontent.com/7413838/92699317-655e4480-f388-11ea-8a40-a60ae99cb8e0.png)

**Comment by hermet** [comment]
If stroke is half-translucent, separate stroke paint and fill paint and give alpha values to each ones.

**Comment by hermet** [comment]
https://github.com/Samsung/thorvg/issues/94
