### ISSUE TITLE
Add new features

### ISSUE THREAD

**Issue by bizehao** [Samsung/thorvg#387]
I want a function to draw points, because I want to draw dot matrix text, please, I like your library, after reading it for a day, I didn’t realize this function

**Comment by hermet** [comment]
@bizehao hi, do you need 1 pixel dot ? or circle?

**Comment by bizehao** [comment]
Yes, I want 1 pixel dot, because I want to draw dot matrix text,  thanks

**Comment by hermet** [comment]
@bizehao thought about this, This is my suggestion.
Thovg basically supports appendCircle(x, y, 1, 1); for the dot though it needs to improve the dot quality (at this moment).
But if you'd like to draw many size of dots, the best approach is to access the canvas buffer and modify the pixel values directly.
That brings the best performance ever than thorvg, even if it provides  a API something like drawDot().

**Comment by bizehao** [comment]
ok,I have already done this and added a similar api
