### ISSUE TITLE
Support Radial Gradient Transformation in SVG

### ISSUE THREAD

**Issue by JSUYA** [Samsung/thorvg#40]
Radial gradient transformation is not yet supported.

**Comment by hermet** [comment]
Come to think of it, thorvg already support Radial Gradient Transfomation.
see => testGradientTransform

Could you elaborate the issue case?

**Comment by JSUYA** [comment]
This is SVG feature support.
GradientTransform for radial gradient in SVG Loader is not implemented yet.

**Comment by mgrudzinska** [comment]
@JSUYA 
we have the following comment in the tvgSwFill.cpp:  "//FIXME; Scale + Rotation is not working properly"
Do you know something more about it? some examples?

I can not find a problem with that:
```
<svg viewBox="0 0 420 200" xmlns="http://www.w3.org/2000/svg">
  <radialGradient id="gradient1" gradientUnits="userSpaceOnUse"
      cx="100" cy="100" r="100" fx="100" fy="100">
    <stop offset="0%" stop-color="darkblue" />
    <stop offset="50%" stop-color="skyblue" />
    <stop offset="100%" stop-color="darkblue" />
  </radialGradient>
  <radialGradient id="gradient2" gradientUnits="userSpaceOnUse"
      cx="100" cy="100" r="100" fx="100" fy="100"
      gradientTransform="scale(2) translate(-50, 0)">
    <stop offset="0%" stop-color="darkblue" />
    <stop offset="50%" stop-color="skyblue" />
    <stop offset="100%" stop-color="darkblue" />
  </radialGradient>

  <rect x="0" y="0" width="200" height="200" fill="url(#gradient1)" />
  <rect x="0" y="0" width="200" height="200" fill="url(#gradient2)" style="transform: translate(220, 0) scale(0.5) rotate(45);" />
</svg>
```

the result from tvg is as expected:
![rad_trnsform](https://user-images.githubusercontent.com/67589014/122482684-52d90180-cfd1-11eb-8f71-4a6582be2fb9.PNG)

**Comment by mgrudzinska** [comment]
@JSUYA  Is that the problem you meant?
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <defs
     id="defs4">
    <radialGradient
       id="radialGradient1"
       r="0.2"
       cx="0.3"
       cy="0.3"
       spreadMethod="reflect">
      <stop
         style="stop-color:#ff0000;stop-opacity:1;"
         offset="0"/>
      <stop
         style="stop-color:#0000ff;stop-opacity:1;"
         offset="1"/>
    </radialGradient>
  </defs>
  <rect x="10" y="0" width="10" height="10" fill="url(#radialGradient1)" transform="scale(2 3) rotate(20) "/>
</svg>
```

tvg result:
![before](https://user-images.githubusercontent.com/67589014/122564787-0d0a5080-d046-11eb-9d4c-668cea6abebf.PNG)

expected result:
![expected](https://user-images.githubusercontent.com/67589014/122564829-198ea900-d046-11eb-8bd5-8e60e4eae620.PNG)

this specific example will work after we solve #37 
or is there some other problem with rotation and scaling?

**Comment by JSUYA** [comment]
> @JSUYA
> we have the following comment in the tvgSwFill.cpp: "//FIXME; Scale + Rotation is not working properly"
> Do you know something more about it? some examples?
> 
> I can not find a problem with that:
> 
> ```
> <svg viewBox="0 0 420 200" xmlns="http://www.w3.org/2000/svg">
>   <radialGradient id="gradient1" gradientUnits="userSpaceOnUse"
>       cx="100" cy="100" r="100" fx="100" fy="100">
>     <stop offset="0%" stop-color="darkblue" />
>     <stop offset="50%" stop-color="skyblue" />
>     <stop offset="100%" stop-color="darkblue" />
>   </radialGradient>
>   <radialGradient id="gradient2" gradientUnits="userSpaceOnUse"
>       cx="100" cy="100" r="100" fx="100" fy="100"
>       gradientTransform="scale(2) translate(-50, 0)">
>     <stop offset="0%" stop-color="darkblue" />
>     <stop offset="50%" stop-color="skyblue" />
>     <stop offset="100%" stop-color="darkblue" />
>   </radialGradient>
> 
>   <rect x="0" y="0" width="200" height="200" fill="url(#gradient1)" />
>   <rect x="0" y="0" width="200" height="200" fill="url(#gradient2)" style="transform: translate(220, 0) scale(0.5) rotate(45);" />
> </svg>
> ```
> 
> the result from tvg is as expected:
> ![rad_trnsform](https://user-images.githubusercontent.com/67589014/122482684-52d90180-cfd1-11eb-8f71-4a6582be2fb9.PNG)

ThorVG's RadialGradient does not yet provide sx, sy scale for Radius.
The issue for that issue is #37 as you say.

This issue is resolved at https://github.com/Samsung/thorvg/pull/460
Therefore, we will close this issue.

Thank you for your work.
