### ISSUE TITLE
SVG to Lottie

### ISSUE THREAD

**Issue by fire** [Samsung/thorvg#405]
Hi 👋 . We've talked before.

I want to propose that there is a workflow for doing SVG to lottie because I couldn't find a satisfactory workflow for SVG-to-Lottie.

Thoughts, Questions, or jokes?

**Comment by hermet** [comment]
@fire good suggestion. it would be hard work actually,  we have a plan to unify rlottie runtime to thorvg first and then we will consider your request though we are not sure yet...

Anyhow, godot could replace rlottie (as far as I know your engine is using rlottie) later if thorvg support it as an extension such as other types of loaders in thorvg.

**Comment by hermet** [comment]
https://lottiefiles.com/svg-to-lottie?gclid=CjwKCAjw6fyXBhBgEiwAhhiZsq_GcTy448b-85Hz6W2LJADMo9Pq7Vskei0-PEetsunvkg5A3pPJ_BoCDbYQAvD_BwE
