### ISSUE TITLE
SVG Mask doesn't work.

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#428]
Try in the example:
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mask

**Comment by mgrudzinska** [comment]
currently TVG doesn't support gradient masks, so it doesn't matter what is it's color.
in the example a color defines the 'mask value' - the alpha value of a mask.

To get a 'mask value' from a color (sRGB) the luminance-to-alpha coefficients has to be applied:
```mask_value = (0.2125 * r + 0.7154 * g + 0.0721 * b ) * a / 255``` 
where `r, g, b` - non premultiplied, `a` in 0-255

I just need to think for a while where to apply this so it won't affect the performance.

**Comment by hermet** [comment]
@mgrudzinska Sounds like tvg need to support CompositeMethod such as ColorMasking or AlphMatte/InvAlphaMatte or similar.

**Comment by mgrudzinska** [comment]
@mmaciola 
https://www.w3.org/TR/SVG11/masking.html#Masking
https://www.w3.org/TR/SVG11/filters.html#feColorMatrixElement    <-    "luminanceToAlpha"

**Comment by mgrudzinska** [comment]
after #620 is applied, #988 is also necessary to make the example work

**Comment by hermet** [comment]
Confirmed it works now. :)
