### ISSUE TITLE
Memory leak: scene->clear(true)

### ISSUE THREAD

**Issue by mmaciola** [Samsung/thorvg#442]
`scene->clear(true)` seems not release all required memory.
Test scenario posted below result in 24,099 definitely lost bytes (456,099 bytes for j<20). 
```
void tvgDrawCmds(tvg::Canvas* canvas)
{
    if (!canvas) return;

    auto scene = tvg::Scene::gen();

    for (int j=0; j<2; j++) {
        scene->clear(true);
        for (int i=0; i<1000; i++) {
            auto shape = tvg::Shape::gen();
            shape->appendRect(10, 10, 100, 100, 20, 20);
            shape->fill(255,0,0, 255);
            scene->push(move(shape));
        }
    }

    canvas->push(move(scene));
}
```

**Comment by mihashco** [comment]
Hello Michal. I think this example is not correct. 1000 objects will always remain unreleased and same results show asan report. After canvas->push there is no command to clear scene or canvas.  Correct way is always: 

1. Create scene
2. Create shapes and push it to scene 
3. Push scene to canvas
4. Draw and sync canvas
5. Cleanup 

So above sequence is a one frame rendering process. You cleanup code at point 5. could looks like this: 

```cpp
canvas->clear(true); 
```
or 
```
scene->clear(true);
```

If you notice memory leak after cleanup then we can check memory leak issue.

**Comment by mmaciola** [comment]
Last 1000 were correctly removed deleting the scene on finish, but the problem was `scene->clear(true)` function itself that didn't remove paints on particular case. I already created patch https://github.com/Samsung/thorvg/pull/446 It fixes memory leak on this snippet

**Comment by mihashco** [comment]
@mmaciola Ok I got your point. It will not be removed correctly because internal issue
