### ISSUE TITLE
Implement API TCT (Unit-Test Suite)

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#45]
We support Unit Tests using catch2 framework

See thorvg Unit Tests
https://github.com/Samsung/thorvg/pull/409

I suggest to separate tasks.

C++: 
Initializer (o) / Paint / Canvas (o) / SwCanvas (o) / Shape (o) / Picture (o) / Fill / RadialGradient / LinearGradient => @hermet 
Scene (o) => @JSUYA

CAPI: 
please make a sub-folder in test (like thorvg/test/capi)
Initializer (o) / Paint (o) / SwCanvas (o) / Shape (o) => @mmaciola 
Fill (o) / RadialGradient (o) / LinearGradient (o) => @mihashco 
Picture (o)  => @hermet 
Scene => @jykeon

**Comment by hermet** [comment]
https://github.com/Samsung/thorvg/pull/125

**Comment by hermet** [comment]
Investigating Catch2 vs GTest.

**Comment by JSUYA** [comment]
I think, someday we may bring TC in thorvg to Tizen test platform, so I recommend use gtest.

**Comment by hermet** [comment]
@JSUYA gtest is not mandatory. I think removing dependency is better for wider system usages.

**Comment by fire** [comment]
We've had a good experience with doctest.

* https://github.com/godotengine/godot/tree/master/tests
* https://github.com/onqtam/doctest
* https://docs.godotengine.org/en/latest/development/cpp/unit_testing.html

**Comment by hermet** [comment]
@fire a little late checked out. thanks for info. :)

**Comment by hermet** [comment]
@mmaciola could you please take over this ?
Picture / Scene => @jykeon

**Comment by hermet** [comment]
Fill / RadialGradient / LinearGradient => @hermet
