### ISSUE TITLE
Incorrect SVG - GOA Account Exchange

### ISSUE THREAD

**Issue by fire** [Samsung/thorvg#455]
[goa-account-exchange.svg.txt](https://github.com/Samsung/thorvg/files/6668472/goa-account-exchange.svg.txt)

`static void _freeNodeStyle(SvgStyleProperty* style)`

**Comment by hermet** [comment]
@fire could you please verify it?

**Comment by fire** [comment]
The SVG doesn't crash but is still wrong.

Left is thorvg and the right is firefox.

![image](https://user-images.githubusercontent.com/32321/122965536-26a8e200-d33d-11eb-8953-4777fee4979a.png)

**Comment by mgrudzinska** [comment]
filters are one problem
parsing the path command 'a' is also an issue here

**Comment by fire** [comment]
There's progress.

I'm reviewing older issues.

![image](https://user-images.githubusercontent.com/32321/123656491-d28e7980-d7e4-11eb-9574-a6fb382bea90.png)

**Comment by hermet** [comment]
![shot-2021-07-11_00-18-08](https://user-images.githubusercontent.com/3711518/125167853-862c3c00-e1dd-11eb-9783-25d018307536.jpg)

**Comment by fire** [comment]
Thanks.
