### ISSUE TITLE
Assorted svg pack with multiple crashes

### ISSUE THREAD

**Issue by fire** [Samsung/thorvg#457]
https://github.com/godotengine/godot/pull/49601#issuecomment-862334524

There is a zip.

## Crashes (not just these ones)
1. e-stop-019.svg
1. speed.svg
2. e-mask-022.svg
3. e-mask-023.svg
4. e-linearGradient-004.svg

**Comment by mgrudzinska** [comment]
e-linearGradient-004.svg -> solved in #470

**Comment by mgrudzinska** [comment]
e-stop-019.svg -> the final solution in #514

**Comment by hermet** [comment]
i think all five issues are fixed. 
The last improvement patch => https://github.com/Samsung/thorvg/pull/539

**Comment by fire** [comment]
Thanks.

I'll close this and when I test the zip again, I'll make new bug reports.
