### ISSUE TITLE
Provide command line tool to open and parse multiple files  

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#459]
Currently I don't see method to be able to test if loading different files will cause memory leaks or crash.

The best way, I think, is to create a command line app which will allow to open multiple files at once e.g.

in folder /home/user/sierra there is 1000 svg files, so command
```
thor-opener /home/user/sierra
```
will open and parse one by one files.

Output should be like this(of course when compiling with sanitizer support):
```
Opening file blabla.svg
Opening file blabla2.svg
Address sanitizer Usage after free:
.....
.....
.....
```
so it will show that `blabla2.svg` cause problems

**Comment by hermet** [comment]
@qarmin Do you satisfy if we provide that kind of sample in thorvg repo?

**Comment by qarmin** [comment]
Yeah, it will be great, for now I tried to use svg2png, but sadly it doesn't compile with address sanitizer

**Comment by hermet** [comment]
i think we can improve the svg2png to allow all svg files in the folder.
example ...
$svg2png *.svg  400x400 ff00ff
$svg2png ./res/*.svg  400x400 ff00ff

**Comment by hermet** [comment]
@JSUYA good idea?
