### ISSUE TITLE
Support Windows lib/dll build envrionment

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#46]
Add windows build script (or vs project) to build/generate thorvg lib/dll files.

**Comment by vtorri** [comment]
i can look at Windows if you want

**Comment by vtorri** [comment]
TVG_EXPORT should be fixed on Windows, I can do something like EAPI is you want

**Comment by hermet** [comment]
@vtorri  yes, please.

**Comment by fire** [comment]
I did some work on msvc, but not sure if this is resolved.
