### ISSUE TITLE
Missing break in tvgLoaderMgr.cpp

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#472]
https://github.com/Samsung/thorvg/blob/f20ef0dc158626b207edfabaa90f86cadb98beb9/src/lib/tvgLoaderMgr.cpp#L83-L91

**Comment by hermet** [comment]
fix by https://github.com/Samsung/thorvg/commit/cadbbb802898aea35b446750c3375af814264565
thanks.

**Comment by hermet** [comment]
@qarmin  fix by https://github.com/Samsung/thorvg/commit/cadbbb802898aea35b446750c3375af814264565
thanks.
