### ISSUE TITLE
Support ClipTo property in SVG

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#49]
We missed to implement clipPath feature in engine side and svg parser.

`
<svg viewBox="0 0 100 100">
  <clipPath id="myClip">
    
    <circle cx="40" cy="35" r="35" />
  </clipPath>
`

This can be accomplished with this interface.

auto shape = tvg::Shape::gen();
...
auto paint = tvg::Shape::gen();
...
paint->composite(shape, ClipTo);

**Comment by hermet** [comment]
Please mind this interfaces for implementing basic maksing model.
enum CompMethod { MaskAlpha };
bool Paint::composite(unique_ptr paint, CompMethod method);

**Comment by JSUYA** [comment]
+ #68

**Comment by JSUYA** [comment]
#91

**Comment by JSUYA** [comment]
now on, SVG clip paths are supported.
