### ISSUE TITLE
InkScape and Firefox render the cube red

### ISSUE THREAD

**Issue by fire** [Samsung/thorvg#515]
https://github.com/godotengine/godot/issues/41339

[icon_voxel_terrain.zip](https://github.com/Samsung/thorvg/files/6716904/icon_voxel_terrain.zip)

InkScape and Firefox render the cube red.

I believe ThorVG and NanoSVG render it blue and red.

**Comment by hermet** [comment]
<path
       d="m8 1051.4-7-3v-8l7 3z"
       id="path4"
       style="fill:#fc9c9c;fill-opacity:0.99607843"
       fill="#68b6ff" />

Here style fill="fc9c9c" should override the color beyond the fill="68b6ff"

But tvg doesn't this...

**Comment by mmaciola** [comment]
I checked the attached file. Blue and red rendering is the expected result: fill is set twice for each wall; once with `fill` attribute that sets bluish color and once with `style="fill:..;"` attribute that sets redish color. For right and top wall, style is set after fill (so style ovewrites fill and wall is redish). For left wall, it is fill attribute that is set last, so wall is properly rendered bluish.

**Comment by Zylann** [comment]
Aren't styles supposed to take precedence over attributes? https://stackoverflow.com/questions/6525405/svg-use-attributes-or-css-to-style/36755226#36755226

**Comment by mgrudzinska** [comment]
style has higher priority than fill, the cube should be red

**Comment by hermet** [comment]
@fire fixed in v0.3.1
