### ISSUE TITLE
Runtime error: load of value 190, which is not a valid value for type 'bool' (svg2png)

### ISSUE THREAD

**Issue by qarmin** [Samsung/thorvg#544]
[e-clipPath-004.svg.zip](https://github.com/Samsung/thorvg/files/6743386/e-clipPath-004.svg.zip)

This means that this value was used without initialization

```
../src/lib/sw_engine/tvgSwRenderer.cpp:148:30: runtime error: load of value 190, which is not a valid value for type 'bool'
```

**Comment by hermet** [comment]
@qarmin fixed by https://github.com/Samsung/thorvg/pull/554
