### ISSUE TITLE
Shape after reset is not rendered properly when multiple draw commands is used 

### ISSUE THREAD

**Issue by mihashco** [Samsung/thorvg#56]
Test code 
`
 tvg_engine_init(TVG_ENGINE_SW | TVG_ENGINE_GL, 0);

    Tvg_Canvas* canvas = tvg_swcanvas_create();
    tvg_swcanvas_set_target(canvas, buffer, WIDTH, WIDTH, HEIGHT, TVG_COLORSPACE_ARGB8888);

    Tvg_Paint* shape = tvg_shape_new();
    tvg_shape_append_rect(shape, 0, 0, 200, 200, 0, 0);
    
    tvg_shape_set_stroke_color(shape, 255, 0, 0, 255);
    tvg_shape_set_stroke_width(shape, 4);
    tvg_shape_set_fill_color(shape, 0, 0, 255, 255);

    tvg_canvas_push(canvas, shape);

    tvg_canvas_draw(canvas);
    tvg_canvas_sync(canvas);

    tvg_shape_reset(shape);
    tvg_canvas_update_paint(canvas, shape);
    
    tvg_canvas_draw(canvas);
    tvg_canvas_sync(canvas);
    tvg_canvas_destroy(canvas);

    tvg_engine_term(TVG_ENGINE_SW | TVG_ENGINE_GL);
`

**Comment by hermet** [comment]
Once shape is reset, it won't be drawn anymore because it's propertie are flushed out.
Did you expect this behavior?

**Comment by mihashco** [comment]
Yes, it should not be draw. Currently only fill is deleted, but path is visible

**Comment by hermet** [comment]
@mihashco ok, i will check it soon. thanks.

**Comment by hermet** [comment]
https://github.com/Samsung/thorvg/pull/99/commits/5864b44e5239d57c86d3c5363928307b9714abd2
