### ISSUE TITLE
Pass filetype to picture::load(data, size, copy)

### ISSUE THREAD

**Issue by mmaciola** [Samsung/thorvg#571]
When we pass data into picture::load, loaders are tried one by one until success.
It is often known what type of data are passed and it would be beneficial (in terms of loading time and memory usage) to pass filetype into picture::load and try the expected loader first.

**Comment by hermet** [comment]
Good Issue.

Here is my brief idea.

picture::load(data, size, string mimeType, copy) ;

if mimeType is given with a specific format name such as "jpeg", "jpg", "png", etc",
it could first try with the mapping table (format - registered loader) first.
