### ISSUE TITLE
TC Line Coverage Up

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#588]
Check current status of line coverage of TC, 
We aim to improve it up to 80%.

What is the best method to verify the Line Coverage?

**Comment by fire** [comment]
Are you using https://samsung.github.io/qaboard/docs/introduction?

See also https://clang.llvm.org/docs/SourceBasedCodeCoverage.html

**Comment by JSUYA** [comment]
meson provides tools to measure line coverage along with meson tests and report the results.

I installed lcov and GenHtml( https://mesonbuild.com/Unit-tests.html#coverage)
```
meson . build -Dtests=true -Db_coverage=true -Dbindings='capi' -Dloaders='svg','png','jpg'
sudo ninja install test coverage-html -C build
```

[Result]
HEAD : bbc0fbb130
[coveragereport.zip](https://github.com/Samsung/thorvg/files/6799244/coveragereport.zip)


![image](https://user-images.githubusercontent.com/7413838/125244740-a3225580-e32a-11eb-8cdc-611d1fdd3518.png)

**Comment by mmaciola** [comment]
Covered `src/bindings/capi` and `loaders`
[coveragereport.zip](https://github.com/Samsung/thorvg/files/6814865/coveragereport.zip)
![Screenshot from 2021-07-14 11-04-53](https://user-images.githubusercontent.com/71131832/125595269-c25788d9-59de-48f4-8a07-500ece71b248.png)

**Comment by mmaciola** [comment]
![Screenshot from 2021-08-19 11-54-46](https://user-images.githubusercontent.com/71131832/130048812-d9e6e657-e5c9-4c58-bd2d-e4ddead05f6e.png)
[coveragereport.zip](https://github.com/Samsung/thorvg/files/7013479/coveragereport.zip)

**Comment by hermet** [comment]
@mmaciola Since on this topic, could you please add tvg saver/loader as well?

**Comment by mgrudzinska** [comment]
![lcov4](https://user-images.githubusercontent.com/67589014/131684117-5b4f8b32-ab80-4809-9cb3-6f5d31d0682b.PNG)

**Comment by hermet** [comment]
@mgrudzinska  @mmaciola @JSUYA thanks for your cowork!

Now, I think we can close this issue.
the maintaining of the TC will be managed in this Wiki Page -> https://github.com/Samsung/thorvg/wiki/Unit-Tests
Please update it whenever you think it's necessary.
