### ISSUE TITLE
ClipPath rendering is wrong

### ISSUE THREAD

**Issue by taehyub** [Samsung/thorvg#598]
Jupiter clip path rendering is wrong when the clip target goes out of view buffer.
![space_reload](https://user-images.githubusercontent.com/9302965/125223354-97249c80-e306-11eb-91ab-ee35ea6f40d3.gif)

**Comment by JSUYA** [comment]
@taehyub Thanks for reporting the issue.
Please let me know the reproducible tvg code or how to reproduce this issue.

**Comment by hermet** [comment]
@taehyub the issue looks resolved on the latest thorvg. Could you please confirm it?

**Comment by taehyub** [comment]
I checked and It works fine, thanks for your cooperation.
