### ISSUE TITLE
Support Bitmap Rendering

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#61]
tvg::Picture should support Bitmap Rendering

auto picture = tvg::Picture::gen();
picture->load(buffer);
...

**Comment by hermet** [comment]
![Uploading ThorVG-raw_image_render_seq.jpg…]()

**Comment by JSUYA** [comment]
https://github.com/Samsung/thorvg/pull/122

**Comment by JSUYA** [comment]
Sequence Diagram Update
(condition : Data load, opacity < 255, with composite)
![image](https://user-images.githubusercontent.com/7413838/97535567-2d29c880-19ff-11eb-8eb7-d2d6b14c1315.png)
