### ISSUE TITLE
svg: Path that works normally doesn't work as mask

### ISSUE THREAD

**Issue by mmaciola** [Samsung/thorvg#619]
```
<svg width="1000" height="1000" viewBox="0 0 1000 1000" xmlns="http://www.w3.org/2000/svg">
	<g fill="red" mask="url(#vg)">
		<rect x="0" y="0" width="1000" height="1000" />
	</g>
	<defs>
		<mask id="vg">
			<rect fill="white" x="0" y="0" width="1000" height="1000" />
			<path fill="black" d="m280 140h15v55l8 10 8-10v-55h15v60l-23 25-23-25z"/>
			<path fill="black" d="m335 140v80h45v-50h-25v10h10v30h-15v-57h18v-13z"/>
		</mask>
	</defs>
</svg>
```
Should be:
![logo_test](https://user-images.githubusercontent.com/71131832/125918690-43cbe46c-2880-4ff5-a9e3-93517dff9488.png)
Is:
![Screenshot from 2021-07-16 10-36-56](https://user-images.githubusercontent.com/71131832/125918755-a729ff0a-80a8-4c04-a0d2-917574336cf2.png)

**Comment by mgrudzinska** [comment]
on the current version of TVG, after #620 is merged it should be solved

**Comment by mgrudzinska** [comment]
@hermet all we need is pr #620 - @mmaciola is the author. there are some changes that have to be done in this pr.
Is that an urgent issue? 
as far as I know Michal will come back to work after new year

**Comment by mmaciola** [comment]
@hermet @mgrudzinska I am officially off till the end of December, but I will be near the computer anyway.
I have just updated the PR #620 and #621

**Comment by mgrudzinska** [comment]
#1124 is also necessary

**Comment by hermet** [comment]
Confirmed it works now :)
