### ISSUE TITLE
JPG image failing to load

### ISSUE THREAD

**Issue by JSUYA** [Samsung/thorvg#652]
jpg image failing to load

The jpg image(logo.jpg) used in PictureJpg example works fine.
![image](https://user-images.githubusercontent.com/7413838/126754765-3e27de17-dd6b-4e2d-b16f-389a75c2640a.png)

But
During the test, there was a jpg file that can not loaded.
![gallery-medium-29](https://user-images.githubusercontent.com/7413838/126755265-ec21d7c7-9ac1-4165-9ff6-952db680f1fd.jpg)
[gallery-medium-29.zip](https://github.com/Samsung/thorvg/files/6867455/gallery-medium-29.zip)

```
./build/src/examples/PictureJpg
tvg engine: software
JPG is not supported. Did you enable JPG Loader?
```

turbojpeg version : 1.5.2

**Comment by mmaciola** [comment]
To be resolve in future.
The image has some internal problem (`Corrupt JPEG data: 24 extraneous bytes before marker 0xe1`) and turbojpeg report a warning, but there is no function (`tjGetErrorCode()`) to differ warning and an error in turbojpeg version 1.5.2. 1.5.2 is now the newest stable apt-get installable version
