### ISSUE TITLE
Add c_std and cpp_std to meson.build default_options

### ISSUE THREAD

**Issue by mmaciola** [Samsung/thorvg#691]
Building on macos (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.9)") displays numerous errors caused by using an old c_std. I suggest defining c_std in meson.build: `default_options : [..., 'c_std=gnu14', 'cpp_std=gnu++14'],`

**Comment by hermet** [comment]
@mmaciola i don't have macos now, could you please submit a patch?
