### ISSUE TITLE
Support Paint Property Customization

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#693]
Godot engine requires the color customization to support theme changing,
https://github.com/godotengine/godot/pull/49645/files
see: change_nsvg_paint_color

We can  consider how interface we can provide for this requirement.

**Comment by JSUYA** [comment]
Does it mean to update the color of the already pushed paint?

How about using ID (string type)?
Before pushing, it seems that user can create an ID based on unique_ptr with provided api or change the property using a user-defined ID.
or If only the ID registered by the user is used, the ID list is registered on the canvas, and the canvas can find the paint corresponding to the ID more quickly.

If the feature is required only in the SVG case, Picture provides an interface for this request and can rebuild SVG.

But does the property customization we want here fit our concept?

**Comment by hermet** [comment]
@fire ok, thanks for your opinion. we gonna strive for the option 1 approach soon, I think it's somewhat necessary for wide usages. Then later we can consider the option 2 additionally. Regardless of the choice, you don't need to worry about the tvg binary design on vulkan. The design is totally transparent to backend engines.

**Comment by fire** [comment]
@hermet The iterator method isn't exposed yet.

Trying to sync schedules. When are you expected to implement the iterator style?

**Comment by hermet** [comment]
@fire It's shame that it's too delaying, these days a little bit busy :(  I'm gonna try to do this hurry. Do you have concrete the expectation  date for this?

**Comment by hermet** [comment]
@fire fyi, im on this task.

**Comment by fire** [comment]
Found time to review. Checking now.

**Comment by fire** [comment]
// if (p_paint->type == NSVG_PAINT_LINEAR_GRADIENT || p_paint->type == NSVG_PAINT_RADIAL_GRADIENT) {
	// 	for (int stop_index = 0; stop_index < p_paint->gradient->nstops; stop_index++) {
	// 		if (p_paint->gradient->stops[stop_index].color << 8 == p_old << 8) {
	// 			p_paint->gradient->stops[stop_index].color = p_new;
	// 		}
	// 	}
	// }

How do you get the number of color stop counts?

**Comment by fire** [comment]
@hermet I was able to get godot and thorvg displaying again.

Am able to continue on this.

**Comment by fire** [comment]
@hermet 

```
std::unique_ptr<tvg::Accessor>
		accessor = tvg::Accessor::gen();
picture = accessor->access(move(picture), convert_tvg_color_func);
```

Do you know how this api changed?

**Comment by hermet** [comment]
@fire its usage is identical, nothing has been changed. problems?

**Comment by fire** [comment]
I wasn't able to make this work.

The code in godot looks for: stop-color, fill and stroke and replaces it with a color look up table. 

https://github.com/godotengine/godot/compare/master...fire:thorvg

**Comment by fire** [comment]
Since I think this is acceptable in my mind for the light dark theme replacement. I'll close the issue.
