### ISSUE TITLE
Support CSS Style in SVG?

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#702]
Still there are demands of this....

**Comment by mgrudzinska** [comment]
I'll start with inline start sheets. I think that the external ones are not so demanded for now (?)

**Comment by mgrudzinska** [comment]
#1142 
#1143 
#1144
I want to introduce the very first version, so files like this:
```
<svg viewBox="0 0 300 300">
<defs>
    <style>
    <![CDATA[
        circle.myCircle {
            fill: red;
            stroke: blue;
        }
        circle {
            fill: green;
            stroke-width: 10;
            stroke: yellow
        }
        svg {
             fill: pink;
        }
    ]]>
</style>
</defs>

<circle cx="100" cy="50" r="50" class="myCircle"/>
<circle cx="100" cy="100" r="50" class="myCircle" style="fill:gray;"/>
<circle cx="100" cy="150" r="50" />
<rect x="0" y="0" width="40" height="40"/>
</svg>
```
will be properly drawn.

assumptions:
- only one class name used as a reference style node
- only one style element in the svg file (easy to change, but I don't know how to use 'title' attrib...)
- CDATA marker is used

in the near future:
- set a style using id
- parse even if CDATA marker was not used

**Comment by JSUYA** [comment]
Wow good :)
I think we can verify this using the e-style-00*.svg sample in the SVG.zip sample discussed here.
(https://github.com/godotengine/godot/pull/49601)
Even if we don't satisfy all the svg files, it will help you set our goals.

I've read your 3 patches. I expect there will create a lot of patches.
How about implementing with one Draft PR? And you can split them into whatever size you think is appropriate or review them all at once, even if it takes time.

**Comment by mgrudzinska** [comment]
#1160 
I'll check this pr one more time and make some comments to make it easier to review

DONE:
- parsing targets in formats: tag, tag.name, .name
- with/without CDATA marker
- works for style defined on the beginning/end of the file
- proper precedence applied

TODO:
- gradient support
- clipath andmasks support
- introduce global targets like svg, g, ...
- other targets formats, like id
- check in the svg2 standard: geometric properties, how to use title (for now only one <style> per svg file) 



```
<svg  viewBox="0 0 300 300">
 <rect x="0" y="0" width="50" height="50" class="moj" />
 <circle cx="50" cy="50" r="20"  stroke="black" stroke-width="3" class="moj" />
 
 <rect x="100" y="0" width="50" height="50" class="moj" style="fill:red"/>
 <circle cx="150" cy="50" r="20"  style="fill:red" stroke="black" stroke-width="3" class="moj" />
 
 <defs>
  <style>
    rect.moj {
        fill: blue;
        stroke: #00ff00;
    }
    .moj {
        fill: red;
        stroke: blue;
        stroke-width: 10;
    }
    circle.moj {
        fill: blue;
        stroke: #00ff00;
    }
  </style>
 </defs>

 <rect x="0" y="50" width="50" height="50" class="moj" />
 <circle cx="50" cy="100" r="20"  stroke="black" stroke-width="3" class="moj" />
 
 <rect x="100" y="50" width="50" height="50" class="moj" style="fill:red"/>
 <circle cx="150" cy="100" r="20" style="fill:red" stroke="black" stroke-width="3" class="moj" />
 
</svg>
```

**Comment by mgrudzinska** [comment]
current status:
https://github.com/Samsung/thorvg/wiki/CSS-Support-in-SVG
