### ISSUE TITLE
Unneeded interpolation for lines

### ISSUE THREAD

**Issue by mmaciola** [Samsung/thorvg#712]
Below is a snippet of lines in different sizes. The lines are unnecessarily interpolated (no scaling there); their color is visually different than expected by developer. 

```
    if (!canvas) return;

    auto shape = tvg::Shape::gen();
    shape->appendRect(0, 0, WIDTH, HEIGHT, 0, 0);
    shape->fill(255, 255, 255, 255);
    if (canvas->push(move(shape)) != tvg::Result::Success) return;

    //Shape 1
    auto shape1 = tvg::Shape::gen();
    shape1->appendRect(50, 50, 100, 100, 0, 0);
    shape1->stroke(23, 56, 81, 255);
    shape1->stroke(1);
    if (canvas->push(move(shape1)) != tvg::Result::Success) return;

    //Shape 2
    auto shape2 = tvg::Shape::gen();
    shape2->appendRect(200, 50, 100, 100, 0, 0);
    shape2->stroke(23, 56, 81, 255);
    shape2->stroke(2);
    if (canvas->push(move(shape2)) != tvg::Result::Success) return;

    //Shape 3
    auto shape3 = tvg::Shape::gen();
    shape3->appendRect(50, 200, 100, 100, 0, 0);
    shape3->stroke(23, 56, 81, 255);
    shape3->stroke(3);
    if (canvas->push(move(shape3)) != tvg::Result::Success) return;

    //Shape 4
    auto shape4 = tvg::Shape::gen();
    shape4->appendRect(200, 200, 100, 100, 0, 0);
    shape4->stroke(23, 56, 81, 255);
    shape4->stroke(4);
    if (canvas->push(move(shape4)) != tvg::Result::Success) return;
```

Result:
![tvg_strokes](https://user-images.githubusercontent.com/71131832/129158392-bdd8c8ca-600b-4c76-b7bf-f640e078e8a7.png)

**Comment by mmaciola** [comment]
Source of the problem is thorvg logic where line with coordinates x, y means the center of a line is pointed in x, y (half of width above and half of width below). It is ok for shape borders but improper for these lines.
Below there is a svg snippet that also shows the problem:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200">
  <line x1="10" y1="85" x2="190" y2="85" stroke="#173851" stroke-width="1" />
  <line x1="10" y1="95" x2="190" y2="95" stroke="#173851" stroke-width="2" />
  <line x1="10" y1="105" x2="190" y2="105" stroke="#173851" stroke-width="3" />
  <line x1="10" y1="115" x2="190" y2="115" stroke="#173851" stroke-width="4" />
</svg>
```
Thorvg:
![line](https://user-images.githubusercontent.com/71131832/129377321-dcb7e028-78d0-4e77-b426-3a7d51a9bec7.png)

**Comment by hermet** [comment]
There are two issues the we need to consider.
1. Width of the line.
2. Anti-Aliasing.

**Comment by hermet** [comment]
![shot-2021-08-18_17-05-51](https://user-images.githubusercontent.com/3711518/129861836-72eb1f36-3484-4922-a36a-f3c6e6a34f82.jpg)

Compared with Cairo (Left) vs ThorVg (Right)

Two result are exactly same

**Comment by mmaciola** [comment]
You're right. I now tested other SVG viewers for Linux, Mac and Windows. Most tested now behaves like Thorvg, only a few behaved differently; all major web browsers tested and graphics editors (photoshop and gimp) behave like Thorvg.
It looks it was a problem of a viewer I tested before.
It looks there is no an issue for SVG in Thorvg.
