### ISSUE TITLE
Support appendSVGPath API

### ISSUE THREAD

**Issue by JSUYA** [Samsung/thorvg#717]
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/curves/path-data

In general (also in EFL), several frameworks provide the feature to append SVG Path as String.
We have a feature to interpret SVG Path in tvgSvgPath.cpp.
If we move svgPathToTvgPath to a common part rather than SVGLoader, we can get Path Commands and Points.

I think we need to consider providing this feature.

**Comment by hermet** [comment]
We can consider it. if we have a real world demand. 

Back to the history, we'd also supported it from the fw side before, but there were no actual usages.

Thus... thinking about apps point of view, 
the reason of using svg path is not to handle the design resource in the programming level. 
User want quickly load svg files delivered from the designers.

Also we already provide the Picture, the most easiest method...

**Comment by JSUYA** [comment]
https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/curves/path-data
https://skia.org/docs/user/modules/pathkit/#fromsvgstringstr
Not sure, but there may be a request from skiasharp(?).
(I won't say there was a demand because it wasn't a direct request.)

I don't think the need for this API is a matter of image resource handling for designers and developers.
I think adding SVGPath is different from loading SVG image.
It is just one of the ways to add a path, 
and I think that providing this kind of feature can be one of the reasons users want to use our library.

As you said, it may not be necessary if there was no actual use in the previous FW.
However, in the previous FW, path addition was a user level api. Isn't it?
Although thorvg considers user level usability, it is a position that considers the usability of backend(?), so I don't think it can be said to be the same as usability with the previous FW.

only...
I think it can be considered just because you can add features with little effort(?).

If you don't think it's necessary, I'm not going to continue talking about the need for this API.

**Comment by hermet** [comment]
I'm not saying it's necessary or not necessary, but I'm not sure about that api.

My opinion is, I haven't seen actual requests from the app users even we expected it would.

Thus we can consider adding it if there were a real world demand.

If you confirm that's necessary api for the apps, you can make a patch.

**Comment by hermet** [comment]
please reopen it if you think it's still valid.
