### ISSUE TITLE
Can't change the loaded image

### ISSUE THREAD

**Issue by mmaciola** [Samsung/thorvg#719]
Once loaded, image can't be changed. Snippet (it's a real scenario that happens using C-api):
```
    if (!canvas) return;

    auto picture = tvg::Picture::gen().release();
    picture->load(EXAMPLE_DIR"/test.jpg");
    picture->size(400, 400);
    if (canvas->push(unique_ptr<tvg::Picture>(picture)) != tvg::Result::Success) return;

    picture->load(EXAMPLE_DIR"/test2.jpg");
```

**Comment by hermet** [comment]
@mmaciola 

* Expected Sequence of TVG:
Prepare -> Push -> Draw -> Sync
Prepare -> Update -> Draw -> Sync

Do we really need to allow this scenario?
Otherwise we can return InsufficientCondition

**Comment by mmaciola** [comment]
I mean the scenario that happens in efl : Prepare -> Load(..) -> Push -> Draw -> Sync -> ...  -> Load(..) -> ... -> Clear(false) -> Push -> Draw -> Sync
