### ISSUE TITLE
Can't compile ThorVG to WebAssembly after "build: Fixed simd options detection"

### ISSUE THREAD

**Issue by mmaciola** [Samsung/thorvg#729]
After changing a logic for neon detection ["build: Fixed simd options detection"](https://github.com/Samsung/thorvg/commit/e3eaa05548bdc9cd366e044de22fe776caa5540e), there is a problem compiling to WebAssembly
```
em++: error: Passing any of -msse, -msse2, -msse3, -mssse3, -msse4.1, -msse4.2, -mavx, -mfpu=neon flags also requires passing -msimd128!
```

**Comment by hermet** [comment]
https://github.com/Samsung/thorvg/commit/2ceee70fcfdb55ff2bc1eec24ee03a87f3cd6276
