### ISSUE TITLE
Support tvg load/export feature in ThorVG Viewer

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#731]
Releasing tvg format is just around the corner, ThorVG Viewer needs to import the tvg files (like svgs) and display the result on the screen. Plus, It can export to tvg files after converting from the svg.

So... here is the brief requirements:

1. Load TVG file & Display its result on the screen.
2. Add a Export Button in the proper location (top right corner?). That button helps user to export tvg files from the current displayed the vector scene.

+Need more think at the design perspective view.
- What if user wants convert many svg files at once? ThorVG could allow loading multiple svg files from the file dialog box and export them altogether?

**Comment by hermet** [comment]
https://github.com/Samsung/thorvg.viewer

**Comment by mmaciola** [comment]
https://github.com/Samsung/thorvg.viewer/pull/2

**Comment by hermet** [comment]
@mmaciola do you have any idea for this?
What if user wants convert many svg files at once? ThorVG could allow loading multiple svg files from the file dialog box and export them altogether?
