### ISSUE TITLE
view size is not concrete in tvg saver.

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#746]
Currently tvg saver writes the view size using paint's bounds() api.
but Scene doesn't get the transformed children geometry, the returned boundary info is incorrect.
Thus picture->size() won't be scaled we expected.

**Comment by hermet** [comment]
one more problem... tvg needs to add the origin of the shapes as well?
INPUT:
scene
 - shape [rect: 100, 100, 200, 200]

save scene to tvg
currenet tvg size => 200x 200
expected tvg size => 300 x 300

**Comment by mgrudzinska** [comment]
isn;t this solved by #805  ?
