### ISSUE TITLE
Optimization of Memory allocations.

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#75]
Here is a overhead list of memory allocation.
We need to consider to reduce the alloc times by somehow.

![vtune_profile](https://user-images.githubusercontent.com/3711518/93863625-aa766500-fcfe-11ea-8d88-5e0b04800ef2.png)

**Comment by rlottie** [comment]
![Uploading Screenshot from 2020-11-04 15-55-51.png…]()

**Comment by rlottie** [comment]
![Screenshot from 2020-11-04 15-55-51](https://user-images.githubusercontent.com/49511420/98079227-cbfa6d00-1eb6-11eb-9faf-ce8c4df25e8b.png)

**Comment by hermet** [comment]
https://github.com/Samsung/thorvg/pull/132

**Comment by smohantty** [comment]
![Screenshot from 2020-11-05 17-05-58](https://user-images.githubusercontent.com/34466874/98213963-32e85680-1f89-11eb-851b-1c336753b7a3.png)

**Comment by vtorri** [comment]
also look at valgrind = callgrind, and kcachegrind
