### ISSUE TITLE
TVG: ClipPath composition doesn't scale properly

### ISSUE THREAD

**Issue by mmaciola** [Samsung/thorvg#751]
If picture size is changed after loading, clippath doesn't scale properly.

Snippet:
```
static unique_ptr<tvg::SwCanvas> swCanvas;

void tvgDrawCmds(tvg::Canvas* canvas)
{
     if (!canvas) return;

     auto picture = tvg::Picture::gen().release();
     picture->load(EXAMPLE_DIR"/test.tvg");
     picture->size(500.0f, 500.0f);
     canvas->push(unique_ptr<tvg::Picture>(picture));

     if (swCanvas->draw() == tvg::Result::Success) {
          swCanvas->sync();
     }

     picture->size(WIDTH, HEIGHT);
     swCanvas->update(picture);
     if (swCanvas->draw() == tvg::Result::Success) {
          swCanvas->sync();
     }
}
void drawSwView(void* data, Eo* obj) {}
```

Preview:
![Screenshot from 2021-08-26 09-59-06](https://user-images.githubusercontent.com/71131832/130925058-91b2daec-afab-49d0-a7c3-3189c8f3e88b.png)

Expected:
![Screenshot from 2021-08-26 10-03-20](https://user-images.githubusercontent.com/71131832/130925178-a5cc2d0e-9791-4008-96dd-c899d4f1dc6e.png)

Live example:
Use thorvg.viewer.2: drag and drop test.tvg and move size slider.

https://user-images.githubusercontent.com/71131832/130927708-59549300-229a-48e8-8c28-16ddfb45b3bc.mp4

**Comment by hermet** [comment]
I guess image clipper has something wrong... tvg rendering engine must be reviewed.
