### ISSUE TITLE
wrong result from TvgSaver + PictureTvg

### ISSUE THREAD

**Issue by mgrudzinska** [Samsung/thorvg#774]
the result from the examples: TvgSaver + PictureTvg sould look like this:
![17expecy](https://user-images.githubusercontent.com/67589014/132144736-74584a03-9c67-48c4-ba81-9239a7151367.PNG)

and it looks now a bit different:
![17before](https://user-images.githubusercontent.com/67589014/132144751-b3a3ba50-e584-40ed-ba70-bd988e65c0d0.PNG)

**Comment by hermet** [comment]
It looks composition breaks the memory chunks....
