### ISSUE TITLE
tvg format issues

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#783]
we have 3 issues observed in tvg format.
1. picture alignment : in case of svg, we manually reset the position by checking the viewbox, in case of tvg that part is missed. this issue might have a relation with https://github.com/Samsung/thorvg/issues/746
2. texts scaling (samsung & glaxy logo size issue).
3. one picture is not visible (in the middle of the screenshot).  need to figure out which one is. 

![shot-2021-09-08_14-00-05](https://user-images.githubusercontent.com/3711518/132449198-b23c2743-7de0-4e83-9a2f-b4cb2572673d.jpg)

**Comment by mgrudzinska** [comment]
ad 3. gradient_stroke.tvg was missing, #784 fixes it

**Comment by mgrudzinska** [comment]
4. the tiger image looks a bit different after saving into tvg format

tvg:
![22before](https://user-images.githubusercontent.com/67589014/132671369-b891758c-c1fa-4646-9363-735b7a289e9d.PNG)

svg:
![22after](https://user-images.githubusercontent.com/67589014/132671395-aefba80e-a156-4772-a2fa-8f85ec33b6f2.PNG)

**Comment by mgrudzinska** [comment]
5. gallardo
![23galard](https://user-images.githubusercontent.com/67589014/132677354-8a47d983-7cf1-4f02-94cd-f58024bd8aef.PNG)

6. code:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <path d="M57,11c40-22,42-2,35,12c8-27-15-20-30-11z" fill="#47b" fill-rule='evenodd'/>
  <path d="M36,56h56c4-60-83-60-86-6c13-16,26-26,36-30l-29,53c20,23,64,26,79-12h-30c0,14-26,12-25-5zM37,43c0-17,26-17,26,0zM39,89c-10,7-42,15-26-16l29-52c-15,6-36,40-37,48c-12,35,14,37,37,20" fill="#47b" fill-rule='evenodd'/>
</svg>
```
![24msie](https://user-images.githubusercontent.com/67589014/132680952-35c44b5c-b421-4a27-9495-aa52eec617ab.PNG)

7. part of the original code:
```
<svg xmlns="http://www.w3.org/2000/svg" id="Penrose_Staircase" viewBox="0 0 372 283">
  <desc>A Penrose Staircase (Optical Illusion)</desc>
    <g id="Layer_1">
        <path fill="#FFFFFF" stroke="#000000" stroke-linecap="round"
stroke-linejoin="round" d="M241.887,18.16l36.924,18l-36.924,18
            l-36.922-18L241.887,18.16z"/>
        <path fill="#FFFFFF" stroke="#000000" stroke-linecap="round"
stroke-linejoin="round" d="M168.041,46.16l36.924-18l36.922,18
            l-36.922,18L168.041,46.16z"/>
    </g>
</svg>
```
![25penroseStairs](https://user-images.githubusercontent.com/67589014/132685464-bd62b380-e818-41b1-a7ea-45c2413989e3.PNG)

**Comment by mgrudzinska** [comment]
ad.2 fix -> https://github.com/Samsung/thorvg/pull/792
ad.1 fix -> https://github.com/Samsung/thorvg/pull/794

**Comment by mgrudzinska** [comment]
ad. 7 could be solved by solving https://github.com/Samsung/thorvg/issues/26
the problem is, that because of the optimization,  the fill from one shape does not overlap the other shape's stroke, since they are one shape.

**Comment by mgrudzinska** [comment]
ad.7 the full penrose-staircase.svg: 
[penrose-staircase.svg.zip](https://github.com/Samsung/thorvg/files/7153746/penrose-staircase.svg.zip)

**Comment by mgrudzinska** [comment]
an svg example without 'viewbox' attribute ('width' and 'height' are present)
[duke_modyfied.svg.zip](https://github.com/Samsung/thorvg/files/7153853/duke_modyfied.svg.zip)

**Comment by hermet** [comment]
check up the situation

![shot-2021-09-14_20-27-07](https://user-images.githubusercontent.com/3711518/133249575-c1aa64d9-6465-4013-8ce2-ce3770e4fc99.jpg)

**Comment by hermet** [comment]
![Uploading shot-2021-09-15_19-43-30.jpg…]()
