### ISSUE TITLE
Support multiple files converter in ThorVG Viewer

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#811]
What if user wants convert many svg files at once? ThorVG could allow loading multiple svg files from the file dialog box and export them altogether?

**Comment by hermet** [comment]
@mmaciola have any idea?

**Comment by mmaciola** [comment]
I think that using wasm Thorvg Viewer to convert multiple files is not the best idea. It is a viewer - great for previewing, validation and basic editing, but it is not a converter software.
For a few files (2-3 files), user can convert them one by one using Thorvg Viewer, but for multiple, the native software should definitely be used. Web applications has limitations there (memory usage, problem downloading multiple files from browser, need for zipping).
Now we have two tools: svg2tvg and svg2png. Maybe we should create some more general converter that would cover [tvg/svg/...]2[png/tvg] (tvg2tvg can update standard version and change compression).
What do you think about such approach and a tool?

**Comment by mmaciola** [comment]
Thorvg Viewer now supports multiple files upload and switching between files. Working on bulk export and other functions

**Comment by hermet** [comment]
@mmaciola great thanks!
