### ISSUE TITLE
Release Official CAPIs

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#829]
TODO:

1 Remove APIs if the default APIs (C++) have been deprecated
2 Remove Beta Tags unless Default APIs are not officially released
3 Synchronize the API description with the default APIs
4 Review & Refine API Docs if its necessary
5 Add missing CAPI Unit Test

**Comment by hermet** [comment]
@mihashco @mgrudzinska please reply here if you think this job is completed.

**Comment by mgrudzinska** [comment]
yes, I think it's done :)
after everything is merged I'd like to double check spelling and all BETA_API tags, but everything should be good

**Comment by mgrudzinska** [comment]
#902 #903 #904 #905
