### ISSUE TITLE
Shapes are sometimes not filled when using update

### ISSUE THREAD

**Issue by MathewP1** [Samsung/thorvg#84]
You can recreate this issue with this example: [example](https://github.com/MathewP1/thorvg/blob/fill_bug/src/examples/testCapiFill.cpp)
Just switch betweent '1' and '2', you will see that some of the shapes are sometimes not drawn.

This happens when we use fill between push and update_paint, like so:
```
shape = tvg_shape_new();
tvg_shape_append_rect(shape, 0, 0, 100, 100, 0, 0);
tvg_shape_push(canvas, shape);
tvg_shape_set_fill_color(shape, 0, 0, 255, 255); // if this was moved up one line, it would always work
tvg_canvas_update_paint(canvas, shape);
tvg_canvas_draw(canvas);
tvg_canvas_sync(canvas);
```

![fill_bug](https://user-images.githubusercontent.com/37028026/94696635-8c7cb600-0337-11eb-8b7d-70e23687e72c.gif)
Whole window should be filled with rectangles, but some of them are not drawn

**Comment by hermet** [comment]
@MathewP1  Will check soon

**Comment by hermet** [comment]
fixed by this: 
https://github.com/Samsung/thorvg/pull/104
