### ISSUE TITLE
Variable Length Arrays (VLA) are not portable

### ISSUE THREAD

**Issue by projectitis** [Samsung/thorvg#844]
Although many compilers support variable length arrays (VLA) - sometimes as extensions - they are not part of the C++ standard. MSVC fails to compile them. The alternative is to create the array using new/delete. Here is a [little info](https://stackoverflow.com/questions/1887097/why-arent-variable-length-arrays-part-of-the-c-standard) about them.

I'm not sure how to generate a patch, but below is the commit replacing 2 VLAS in `src/loaders/tvg/tvgTvgBinInterpreter.cpp` on my fork: https://github.com/DeriveSDK/thorvg/commit/6562e77e25ac3e9126b4f8a5663b9ae951b11858

I have also noticed VLAs used in a couple of places in the examples. If you verify that this patch is ok (or suggest an alternative if not) I will create PRs for any others I come across. 

An alternative, of course, is not to support MSVC, which seems to be a bit backwards compared to many other c++ compilers!

Thanks for reminding me, @mgrudzinska :) This was raised and split from #824

**Comment by mgrudzinska** [comment]
you have to fork ThorVG, create a new branch (from the current/updated master branch), make changes that you think are necessary, commit them and push. Then on github it will be easy, since github will ask u whether you want to create a pull request. 
Please let us know if u need some help with that. 
Compiling on linux with the 'pedentic' flag gives a waring regarding this topic, and since u find it, it'd be cool if you'd be the author of pr, that fixes it :))

**Comment by mgrudzinska** [comment]
![s1](https://user-images.githubusercontent.com/67589014/135172729-82fca67d-cc90-41e3-be66-8421b82a2992.PNG)
![s2](https://user-images.githubusercontent.com/67589014/135172736-f30ff8ce-1077-430f-a81f-a61a086c3670.PNG)

**Comment by mgrudzinska** [comment]
u can do it from your current repo :)

**Comment by projectitis** [comment]
Yes, that's I would normally do,. but you asked for a patch and I misunderstood - sorry!

**Comment by projectitis** [comment]
Code design question: Is ThorVG generally trying to avoid compiler-conditional code? E.g.
````
if MSVC
  Do it this way
else
  Do it this way
````
I'd like to know if you would prefer a single (non-conditional) solution that is portable, or a conditional one?
The reason is that I can use _malloca (to allocate stack memory) on MSVC, but it's not portable either :)

**Comment by mgrudzinska** [comment]
> Yes, that's I would normally do, but you asked for a patch and I misunderstood - sorry!
I'm sorry :)

I know it's not exactly answers your question, but in this case u can use 'new' and in this way solve the problem for all platforms, right?

**Comment by projectitis** [comment]
Yes, that is correct. The difference is that 'new' allocates memory on the heap, and _malloca allocates memory on the stack (the same way that the original VLA code would do it). Stack is generally better for performance.

**Comment by mgrudzinska** [comment]
Right, so in 'src/loaders/svg/tvgXmlParser.cpp' we use 'alloca' and make two different includes
but if u think that some other way is better, please use it. You could also make some comments in your pr. 
Please chose Hermet as your reviewer. I'd like to know his opinion on this subject

**Comment by projectitis** [comment]
Perfect. Thank you.

**Comment by hermet** [comment]
@projectitis @mgrudzinska looks resolved issue, am i right? can you close it if so?

**Comment by projectitis** [comment]
Sorry @hermet for the delay. Feel free to close this. If any further issues they can be raised separately.

**Comment by hermet** [comment]
@projectitis good thanks!
