### ISSUE TITLE
Host the documentation

### ISSUE THREAD

**Issue by projectitis** [Samsung/thorvg#856]
It would be great if the documentation could be hosted as a website!
Is this possible using github? All the html is already in the docs folder :)
Or would this require a separate website?

**Comment by hermet** [comment]
@projectitis here? https://www.thorvg.org/apis

**Comment by projectitis** [comment]
Thanks! It doesn't come up when searching Google. Hopefully adding it to the readme will generate some more 'Google juice' :)
