### ISSUE TITLE
gl_engine: Use of attribute 'fallthrough' not supported until c++17

### ISSUE THREAD

**Issue by projectitis** [Samsung/thorvg#863]
The file `gl_engine/tvgGlGeometry.cpp` contains the attribute `__attribute__ ((fallthrough));`.  This attribute tells the compiler that the fallthough in the case statement (not including `break`) is intentional.

There are two issues:

1. Fallthrough is only defined from c++17 onwards (default for ThorVG is c++14)
2. MSVC also does not recognise `__attribute__ ((fallthrough));` which must be replaced with `[[fallthrough]]`

**Comment by projectitis** [comment]
If you think it is a good idea, could someone please add a new `label` for `portability`? This covers any changes to ensure code works across different compilers and different platforms.

**Comment by hermet** [comment]
@projectitis added the label, thanks!
