### ISSUE TITLE
Floats comparison

### ISSUE THREAD

**Issue by mgrudzinska** [Samsung/thorvg#88]
fabs(a-b) < FLT_EPSILON
does not work very well for 'a' and 'b' being floats

**Comment by hermet** [comment]
@mgrudzinska Could you please describe more details about it?  what does mean by "does not work very well" ? does it introduce any crashes? or invalid computation? then what float values occur?

**Comment by mgrudzinska** [comment]
A float variable can hold ~8 digits (in general it depends).
FLT_EPSILON is ~1.2e-7 (in my case, in general it's <= 1e-5)

Let's consider 3 cases:

1) a = 1.2345678e0
    b = 1.2345679e0
    b - a = 0.0000001e0 = 1e-7 < FLT_EPSILON - as expected

2) a = 1.2345678e4
    b = 1.2345679e4
    b - a = 0.0000001e4 = 1e-3 > FLT_EPSILON - most probably we expected a different result, but it's not possible to compare  'a' and 'b' with such precision

3) a = 1.2345678e-4
    b = 1.2349999e-4
    b - a = 0.0004321e-4 = 4.321e-8 < FLT_EPSILON - in this case the value of epsilon seems to be too high


Let's consider another example: 

while (fabs(f(x) - f(c)) < FLT_EPSILON)
{
   make 'x' closer and closer to 'c'
}

If the 'f' function is too steep, we may need to change 'x' (in order to stop the while loop) with a much higher precision than this given for a float variable. 
So there are two problems: 
1. as described above with choosing the epsilon value
2. the condition should take into account, that at some point changing (like adding a very small value) 'x' value may not really change it, because we don't have sufficient precision - than we get an infinite loop

**Comment by mgrudzinska** [comment]
Dash pattern values:
The solution presented in #100 with FLT_EPSILON will fail if the ratio of the total curve length and the 'length' value from a dash pattern is >~10^7.
E.g. for the line from (0, 0) to (2.5e4, 2.5e4) and dash pattern (length and gap) values smaller than [3e-3, 3e-3] the termination condition in the while loop will be never satisfied. 
But this example dosn't seem to be realistic. 

Bezier curve splitting:
I'd like to get a little more time to think about this case. I still think it is possible (and it should be also easy) to find an example which will crash, because of FLT_EPSILON usage.

**Comment by mgrudzinska** [comment]
The solution could be to use nextafter function:
fabs(a-b) < nextafter(a,b) - a
but the call for this function instead of a macro needs to be justified

**Comment by hermet** [comment]
We can introduce our own FLT_EPSION definition if the accuracy is not proper. ie) BEZIER_EPSILON.
