### ISSUE TITLE
Introduce Paint Opacity method

### ISSUE THREAD

**Issue by hermet** [Samsung/thorvg#94]
For better flexible usage, I'm considering to separate alpha from color like this:

+ Paint::opacity(a);
* Shape::fill(r, g, b, a) - > Shape::color(r, g, b);
* Shape::stroke(r, g, b, a) -> Shape::stroke(r, g, b);

In this case, user could toggle on/off of paint by opacity change (255 <-> 0) 

Also, it's easier to change scene opacity by this
scene->opacity(127);

Related Issue:
https://github.com/Samsung/thorvg/issues/38

**Comment by hermet** [comment]
@JSUYA Could you please review above method for svg support feasibility?

**Comment by JSUYA** [comment]
I think you can close this issue https://github.com/Samsung/thorvg/pull/120

**Comment by hermet** [comment]
main logic in composition level doesn't satisfied yet.

**Comment by hermet** [comment]
https://github.com/Samsung/thorvg/pull/160

**Comment by hermet** [comment]
https://github.com/Samsung/thorvg/pull/166
